## MASUKKAN LIBRARY YANG DIGUNAKAN

In [51]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [52]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\pjbac\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

## LOAD DATASET

In [53]:
data = pd.read_csv('dataset_transkrip_ujiportfolio1.csv', encoding='Windows-1252')
data.head()

                                                teks  label
0  iya siap pak, masih masih di situ Pak surat pe...      0
1  siap, siap Pak, hari ini saya lengkapi foto be...      0
2  izin Pak, untuk sekarang saya di bagian pelaya...      0
3  iya administrasi Pak tapi posisinya sudah tida...      1
4  ini level 2 kalau nggak salah Pak petugas lapa...      1

## TEXT PREPROCESSING

## CASE FOLDING

In [54]:
import re

# membuat fungsi untuk case folding
def casefolding(text):
    text = text.lower()                                 # mengubah text menjadi huruf kecil
    text = re.sub(r'https?://\S+|www\.S+', '', text)    # menghapus url dari kalimat
    text = re.sub(r'[^\w\s]', '', text)                 # menghapus tanda baca
    text = text.strip()
    return text

In [55]:
# membandingkan before dan after casefolding
raw_sample = data['teks'].iloc[2]
case_folding = casefolding(raw_sample)

print('Raw data\t : ',raw_sample)
print('Case Folding\t : ',case_folding)

Raw data	 :  izin Pak, untuk sekarang saya di bagian pelayanan pelanggan Pak untuk surat tidak ada sih Pak kalau untuk sekarang untuk penetapan untuk kami disini seluruhnya sudah di bagian transaksi energi Pak P2TL pernah Pak, pernah ikut untuk bulan Maret kemarin Pak ini kebetulan saya ada surat tugasnya enggak ada untuk surat tugas
mungkin saya sudah foto karena untuk penetapan sekarang semua sudah murni dari transaksi energi Pak jadi kami mungkin bagian pelayanan pelanggan itu hanya melobby saja ke pelanggan, mungkin ada pelanggan yang komplain, itu kami ke sana untuk bantu media menetapkan ya, halo siap, baik Pak, halo halo Pak tidak hadir pertama kali panggilan, selanjutnya apa? untuk kita kirimkan surat panggilan Pak, ya ya
pertama enggak datang, terus selanjutnya?
terus kita teruskan lagi untuk surat panggilan kedua
pertama dan kedua itu jaraknya berapa hari?
untuk jaraknya satu minggu Pak saya masih mengikuti yang perdir 88 untuk perdir baru saya belum dapat sih Pak terus panggilan kedua enggak datang terus selanjutnya apa?
masuk panggilan ketiga Pak
berapa hari jadwal waktunya?
itu satu minggu juga Pak untuk perdir saya belum dapat sih Pak untuk surat BA nya itu kita lihat untuk untuk nomor surat, tanggal, terus nama, nama pelanggan nama petugas, beserta dengan jabatan Pak nama dan alamat pelanggan di pelanggan dan tersambung peruntukan apa Pak selanjutnya ada data dan barang bukti yang diambil itu diisi semua untuk meter KWH nya, terus tim P2TL mulai dari ketua petugas, penyidik dan saksi Pak untuk selanjutnya Pemeriksaan APP untuk Pemeriksaan APP nya itu ada data KWH, merek tahun, putaran, segel terpasang terus Pembatas kotak APP, dan terakhir kesimpulan dan hasil Pemeriksaan Pak dan tindakan yang dilakukan demikian Pak itu mas untuk segel rusak itu masuk di pelanggaran P2 Pak misalnya rusaknya di rusak sengaja jadi belum untuk P2 udah tau mas P2TL P2TL terakhir Pak saya masih mengikuti yang 2023 tadi saya belum tau sih Pak
Case Folding	 :  izin pak untuk sekarang saya di bagian pelayanan pelanggan pak untuk surat tidak ada sih pak kalau untuk sekarang untuk penetapan untuk kami disini seluruhnya sudah di bagian transaksi energi pak p2tl pernah pak pernah ikut untuk bulan maret kemarin pak ini kebetulan saya ada surat tugasnya enggak ada untuk surat tugas
mungkin saya sudah foto karena untuk penetapan sekarang semua sudah murni dari transaksi energi pak jadi kami mungkin bagian pelayanan pelanggan itu hanya melobby saja ke pelanggan mungkin ada pelanggan yang komplain itu kami ke sana untuk bantu media menetapkan ya halo siap baik pak halo halo pak tidak hadir pertama kali panggilan selanjutnya apa untuk kita kirimkan surat panggilan pak ya ya
pertama enggak datang terus selanjutnya
terus kita teruskan lagi untuk surat panggilan kedua
pertama dan kedua itu jaraknya berapa hari
untuk jaraknya satu minggu pak saya masih mengikuti yang perdir 88 untuk perdir baru saya belum dapat sih pak terus panggilan kedua enggak datang terus selanjutnya apa
masuk panggilan ketiga pak
berapa hari jadwal waktunya
itu satu minggu juga pak untuk perdir saya belum dapat sih pak untuk surat ba nya itu kita lihat untuk untuk nomor surat tanggal terus nama nama pelanggan nama petugas beserta dengan jabatan pak nama dan alamat pelanggan di pelanggan dan tersambung peruntukan apa pak selanjutnya ada data dan barang bukti yang diambil itu diisi semua untuk meter kwh nya terus tim p2tl mulai dari ketua petugas penyidik dan saksi pak untuk selanjutnya pemeriksaan app untuk pemeriksaan app nya itu ada data kwh merek tahun putaran segel terpasang terus pembatas kotak app dan terakhir kesimpulan dan hasil pemeriksaan pak dan tindakan yang dilakukan demikian pak itu mas untuk segel rusak itu masuk di pelanggaran p2 pak misalnya rusaknya di rusak sengaja jadi belum untuk p2 udah tau mas p2tl p2tl terakhir pak saya masih mengikuti yang 2023 tadi saya belum tau sih pak

## WORD NORMALIZATION

In [56]:
key_norm = pd.read_csv('key_norm.csv')

def text_normalize(text):
    text = ' '.join([key_norm[key_norm['singkat'] == word]['hasil'].values[0]
    if (key_norm['singkat'] == word).any()
    else word for word in text.split()
    ])

    text = str.lower(text)
    return text

In [57]:
# membandingkan before dan after word normalization

raw_data = data['teks'].iloc[2]
word_normal = text_normalize(case_folding)

print('Raw Data\t :',raw_data)
print('Word Normalize\t :',word_normal)

Raw Data	 : izin Pak, untuk sekarang saya di bagian pelayanan pelanggan Pak untuk surat tidak ada sih Pak kalau untuk sekarang untuk penetapan untuk kami disini seluruhnya sudah di bagian transaksi energi Pak P2TL pernah Pak, pernah ikut untuk bulan Maret kemarin Pak ini kebetulan saya ada surat tugasnya enggak ada untuk surat tugas
mungkin saya sudah foto karena untuk penetapan sekarang semua sudah murni dari transaksi energi Pak jadi kami mungkin bagian pelayanan pelanggan itu hanya melobby saja ke pelanggan, mungkin ada pelanggan yang komplain, itu kami ke sana untuk bantu media menetapkan ya, halo siap, baik Pak, halo halo Pak tidak hadir pertama kali panggilan, selanjutnya apa? untuk kita kirimkan surat panggilan Pak, ya ya
pertama enggak datang, terus selanjutnya?
terus kita teruskan lagi untuk surat panggilan kedua
pertama dan kedua itu jaraknya berapa hari?
untuk jaraknya satu minggu Pak saya masih mengikuti yang perdir 88 untuk perdir baru saya belum dapat sih Pak terus panggilan kedua enggak datang terus selanjutnya apa?
masuk panggilan ketiga Pak
berapa hari jadwal waktunya?
itu satu minggu juga Pak untuk perdir saya belum dapat sih Pak untuk surat BA nya itu kita lihat untuk untuk nomor surat, tanggal, terus nama, nama pelanggan nama petugas, beserta dengan jabatan Pak nama dan alamat pelanggan di pelanggan dan tersambung peruntukan apa Pak selanjutnya ada data dan barang bukti yang diambil itu diisi semua untuk meter KWH nya, terus tim P2TL mulai dari ketua petugas, penyidik dan saksi Pak untuk selanjutnya Pemeriksaan APP untuk Pemeriksaan APP nya itu ada data KWH, merek tahun, putaran, segel terpasang terus Pembatas kotak APP, dan terakhir kesimpulan dan hasil Pemeriksaan Pak dan tindakan yang dilakukan demikian Pak itu mas untuk segel rusak itu masuk di pelanggaran P2 Pak misalnya rusaknya di rusak sengaja jadi belum untuk P2 udah tau mas P2TL P2TL terakhir Pak saya masih mengikuti yang 2023 tadi saya belum tau sih Pak
Word Normalize	 : izin pak untuk sekarang saya di bagian pelayanan pelanggan pak untuk surat tidak ada sih pak kalau untuk sekarang untuk penetapan untuk kami disini seluruhnya sudah di bagian transaksi energi pak p2tl pernah pak pernah ikut untuk bulan maret kemarin pak ini kebetulan saya ada surat tugasnya enggak ada untuk surat tugas mungkin saya sudah foto karena untuk penetapan sekarang semua sudah murni dari transaksi energi pak jadi kami mungkin bagian pelayanan pelanggan itu hanya melobby saja ke pelanggan mungkin ada pelanggan yang komplain itu kami ke sana untuk bantu media menetapkan ya halo siap baik pak halo halo pak tidak hadir pertama kali panggilan selanjutnya apa untuk kita kirimkan surat panggilan pak ya ya pertama enggak datang terus selanjutnya terus kita teruskan lagi untuk surat panggilan kedua pertama dan kedua itu jaraknya berapa hari untuk jaraknya satu minggu pak saya masih mengikuti yang perdir 88 untuk perdir baru saya belum dapat sih pak terus panggilan kedua enggak datang terus selanjutnya apa masuk panggilan ketiga pak berapa hari jadwal waktunya itu satu minggu juga pak untuk perdir saya belum dapat sih pak untuk surat ba nya itu kita lihat untuk untuk nomor surat tanggal terus nama nama pelanggan nama petugas beserta dengan jabatan pak nama dan alamat pelanggan di pelanggan dan tersambung peruntukan apa pak selanjutnya ada data dan barang bukti yang diambil itu diisi semua untuk meter kwh nya terus tim p2tl mulai dari ketua petugas penyidik dan saksi pak untuk selanjutnya pemeriksaan app untuk pemeriksaan app nya itu ada data kwh merek tahun putaran segel terpasang terus pembatas kotak app dan terakhir kesimpulan dan hasil pemeriksaan pak dan tindakan yang dilakukan demikian pak itu mas untuk segel rusak itu masuk di pelanggaran p2 pak misalnya rusaknya di rusak sengaja jadi belum untuk p2 sudah tau mas p2tl p2tl terakhir pak saya masih mengikuti yang 2023 tadi saya belum tau sih pak

## STOPWORD REMOVAL (FILTERING)

In [58]:
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords

stopwords_ind = stopwords.words('indonesian')

In [59]:
len(stopwords_ind)

758

In [60]:
# melihat daftar stopwords dari nltk
stopwords_ind

['ada',
 'adalah',
 'adanya',
 'adapun',
 'agak',
 'agaknya',
 'agar',
 'akan',
 'akankah',
 'akhir',
 'akhiri',
 'akhirnya',
 'aku',
 'akulah',
 'amat',
 'amatlah',
 'anda',
 'andalah',
 'antar',
 'antara',
 'antaranya',
 'apa',
 'apaan',
 'apabila',
 'apakah',
 'apalagi',
 'apatah',
 'artinya',
 'asal',
 'asalkan',
 'atas',
 'atau',
 'ataukah',
 'ataupun',
 'awal',
 'awalnya',
 'bagai',
 'bagaikan',
 'bagaimana',
 'bagaimanakah',
 'bagaimanapun',
 'bagi',
 'bagian',
 'bahkan',
 'bahwa',
 'bahwasanya',
 'baik',
 'bakal',
 'bakalan',
 'balik',
 'banyak',
 'bapak',
 'baru',
 'bawah',
 'beberapa',
 'begini',
 'beginian',
 'beginikah',
 'beginilah',
 'begitu',
 'begitukah',
 'begitulah',
 'begitupun',
 'bekerja',
 'belakang',
 'belakangan',
 'belum',
 'belumlah',
 'benar',
 'benarkah',
 'benarlah',
 'berada',
 'berakhir',
 'berakhirlah',
 'berakhirnya',
 'berapa',
 'berapakah',
 'berapalah',
 'berapapun',
 'berarti',
 'berawal',
 'berbagai',
 'berdatangan',
 'beri',
 'berikan',
 'berikut',
 'berikutnya',
 'berjumlah',
 'berkali-kali',
 'berkata',
 'berkehendak',
 'berkeinginan',
 'berkenaan',
 'berlainan',
 'berlalu',
 'berlangsung',
 'berlebihan',
 'bermacam',
 'bermacam-macam',
 'bermaksud',
 'bermula',
 'bersama',
 'bersama-sama',
 'bersiap',
 'bersiap-siap',
 'bertanya',
 'bertanya-tanya',
 'berturut',
 'berturut-turut',
 'bertutur',
 'berujar',
 'berupa',
 'besar',
 'betul',
 'betulkah',
 'biasa',
 'biasanya',
 'bila',
 'bilakah',
 'bisa',
 'bisakah',
 'boleh',
 'bolehkah',
 'bolehlah',
 'buat',
 'bukan',
 'bukankah',
 'bukanlah',
 'bukannya',
 'bulan',
 'bung',
 'cara',
 'caranya',
 'cukup',
 'cukupkah',
 'cukuplah',
 'cuma',
 'dahulu',
 'dalam',
 'dan',
 'dapat',
 'dari',
 'daripada',
 'datang',
 'dekat',
 'demi',
 'demikian',
 'demikianlah',
 'dengan',
 'depan',
 'di',
 'dia',
 'diakhiri',
 'diakhirinya',
 'dialah',
 'diantara',
 'diantaranya',
 'diberi',
 'diberikan',
 'diberikannya',
 'dibuat',
 'dibuatnya',
 'didapat',
 'didatangkan',
 'digunakan',
 'diibaratkan',
 'diibaratkannya',
 'diingat',
 'diingatkan',
 'diinginkan',
 'dijawab',
 'dijelaskan',
 'dijelaskannya',
 'dikarenakan',
 'dikatakan',
 'dikatakannya',
 'dikerjakan',
 'diketahui',
 'diketahuinya',
 'dikira',
 'dilakukan',
 'dilalui',
 'dilihat',
 'dimaksud',
 'dimaksudkan',
 'dimaksudkannya',
 'dimaksudnya',
 'diminta',
 'dimintai',
 'dimisalkan',
 'dimulai',
 'dimulailah',
 'dimulainya',
 'dimungkinkan',
 'dini',
 'dipastikan',
 'diperbuat',
 'diperbuatnya',
 'dipergunakan',
 'diperkirakan',
 'diperlihatkan',
 'diperlukan',
 'diperlukannya',
 'dipersoalkan',
 'dipertanyakan',
 'dipunyai',
 'diri',
 'dirinya',
 'disampaikan',
 'disebut',
 'disebutkan',
 'disebutkannya',
 'disini',
 'disinilah',
 'ditambahkan',
 'ditandaskan',
 'ditanya',
 'ditanyai',
 'ditanyakan',
 'ditegaskan',
 'ditujukan',
 'ditunjuk',
 'ditunjuki',
 'ditunjukkan',
 'ditunjukkannya',
 'ditunjuknya',
 'dituturkan',
 'dituturkannya',
 'diucapkan',
 'diucapkannya',
 'diungkapkan',
 'dong',
 'dua',
 'dulu',
 'empat',
 'enggak',
 'enggaknya',
 'entah',
 'entahlah',
 'guna',
 'gunakan',
 'hal',
 'hampir',
 'hanya',
 'hanyalah',
 'hari',
 'harus',
 'haruslah',
 'harusnya',
 'hendak',
 'hendaklah',
 'hendaknya',
 'hingga',
 'ia',
 'ialah',
 'ibarat',
 'ibaratkan',
 'ibaratnya',
 'ibu',
 'ikut',
 'ingat',
 'ingat-ingat',
 'ingin',
 'inginkah',
 'inginkan',
 'ini',
 'inikah',
 'inilah',
 'itu',
 'itukah',
 'itulah',
 'jadi',
 'jadilah',
 'jadinya',
 'jangan',
 'jangankan',
 'janganlah',
 'jauh',
 'jawab',
 'jawaban',
 'jawabnya',
 'jelas',
 'jelaskan',
 'jelaslah',
 'jelasnya',
 'jika',
 'jikalau',
 'juga',
 'jumlah',
 'jumlahnya',
 'justru',
 'kala',
 'kalau',
 'kalaulah',
 'kalaupun',
 'kalian',
 'kami',
 'kamilah',
 'kamu',
 'kamulah',
 'kan',
 'kapan',
 'kapankah',
 'kapanpun',
 'karena',
 'karenanya',
 'kasus',
 'kata',
 'katakan',
 'katakanlah',
 'katanya',
 'ke',
 'keadaan',
 'kebetulan',
 'kecil',
 'kedua',
 'keduanya',
 'keinginan',
 'kelamaan',
 'kelihatan',
 'kelihatannya',
 'kelima',
 'keluar',
 'kembali',
 'kemudian',
 'kemungkinan',
 'kemungkinannya',
 'kenapa',
 'kepada',
 'kepadanya',
 'kesampaian',
 'keseluruhan',
 'keseluruhannya',
 'keterlaluan',
 'ketika',
 'khususnya',
 'kini',
 'kinilah',
 'kira',
 'kira-kira',
 'kiranya',
 'kita',
 'kitalah',
 'kok',
 'kurang',
 'lagi',
 'lagian',
 'lah',
 'lain',
 'lainnya',
 'lalu',
 'lama',
 'lamanya',
 'lanjut',
 'lanjutnya',
 'lebih',
 'lewat',
 'lima',
 'luar',
 'macam',
 'maka',
 'makanya',
 'makin',
 'malah',
 'malahan',
 'mampu',
 'mampukah',
 'mana',
 'manakala',
 'manalagi',
 'masa',
 'masalah',
 'masalahnya',
 'masih',
 'masihkah',
 'masing',
 'masing-masing',
 'mau',
 'maupun',
 'melainkan',
 'melakukan',
 'melalui',
 'melihat',
 'melihatnya',
 'memang',
 'memastikan',
 'memberi',
 'memberikan',
 'membuat',
 'memerlukan',
 'memihak',
 'meminta',
 'memintakan',
 'memisalkan',
 'memperbuat',
 'mempergunakan',
 'memperkirakan',
 'memperlihatkan',
 'mempersiapkan',
 'mempersoalkan',
 'mempertanyakan',
 'mempunyai',
 'memulai',
 'memungkinkan',
 'menaiki',
 'menambahkan',
 'menandaskan',
 'menanti',
 'menanti-nanti',
 'menantikan',
 'menanya',
 'menanyai',
 'menanyakan',
 'mendapat',
 'mendapatkan',
 'mendatang',
 'mendatangi',
 'mendatangkan',
 'menegaskan',
 'mengakhiri',
 'mengapa',
 'mengatakan',
 'mengatakannya',
 'mengenai',
 'mengerjakan',
 'mengetahui',
 'menggunakan',
 'menghendaki',
 'mengibaratkan',
 'mengibaratkannya',
 'mengingat',
 'mengingatkan',
 'menginginkan',
 'mengira',
 'mengucapkan',
 'mengucapkannya',
 'mengungkapkan',
 'menjadi',
 'menjawab',
 'menjelaskan',
 'menuju',
 'menunjuk',
 'menunjuki',
 'menunjukkan',
 'menunjuknya',
 'menurut',
 'menuturkan',
 'menyampaikan',
 'menyangkut',
 'menyatakan',
 'menyebutkan',
 'menyeluruh',
 'menyiapkan',
 'merasa',
 'mereka',
 'merekalah',
 'merupakan',
 'meski',
 'meskipun',
 'meyakini',
 'meyakinkan',
 'minta',
 'mirip',
 'misal',
 'misalkan',
 'misalnya',
 'mula',
 'mulai',
 'mulailah',
 'mulanya',
 'mungkin',
 'mungkinkah',
 'nah',
 'naik',
 'namun',
 'nanti',
 'nantinya',
 'nyaris',
 'nyatanya',
 'oleh',
 'olehnya',
 'pada',
 'padahal',
 'padanya',
 'pak',
 'paling',
 'panjang',
 'pantas',
 'para',
 'pasti',
 'pastilah',
 'penting',
 'pentingnya',
 'per',
 'percuma',
 'perlu',
 'perlukah',
 'perlunya',
 'pernah',
 'persoalan',
 'pertama',
 'pertama-tama',
 'pertanyaan',
 'pertanyakan',
 'pihak',
 'pihaknya',
 'pukul',
 'pula',
 'pun',
 'punya',
 'rasa',
 'rasanya',
 'rata',
 'rupanya',
 'saat',
 'saatnya',
 'saja',
 'sajalah',
 'saling',
 'sama',
 'sama-sama',
 'sambil',
 'sampai',
 'sampai-sampai',
 'sampaikan',
 'sana',
 'sangat',
 'sangatlah',
 'satu',
 'saya',
 'sayalah',
 'se',
 'sebab',
 'sebabnya',
 'sebagai',
 'sebagaimana',
 'sebagainya',
 'sebagian',
 'sebaik',
 'sebaik-baiknya',
 'sebaiknya',
 'sebaliknya',
 'sebanyak',
 'sebegini',
 'sebegitu',
 'sebelum',
 'sebelumnya',
 'sebenarnya',
 'seberapa',
 'sebesar',
 'sebetulnya',
 'sebisanya',
 'sebuah',
 'sebut',
 'sebutlah',
 'sebutnya',
 'secara',
 'secukupnya',
 'sedang',
 'sedangkan',
 'sedemikian',
 'sedikit',
 'sedikitnya',
 'seenaknya',
 'segala',
 'segalanya',
 'segera',
 'seharusnya',
 'sehingga',
 'seingat',
 'sejak',
 'sejauh',
 'sejenak',
 'sejumlah',
 'sekadar',
 'sekadarnya',
 'sekali',
 'sekali-kali',
 'sekalian',
 'sekaligus',
 'sekalipun',
 'sekarang',
 'sekarang',
 'sekecil',
 'seketika',
 'sekiranya',
 'sekitar',
 'sekitarnya',
 'sekurang-kurangnya',
 'sekurangnya',
 'sela',
 'selain',
 'selaku',
 'selalu',
 'selama',
 'selama-lamanya',
 'selamanya',
 'selanjutnya',
 'seluruh',
 'seluruhnya',
 'semacam',
 'semakin',
 'semampu',
 'semampunya',
 'semasa',
 'semasih',
 'semata',
 'semata-mata',
 'semaunya',
 'sementara',
 'semisal',
 'semisalnya',
 'sempat',
 'semua',
 'semuanya',
 'semula',
 'sendiri',
 'sendirian',
 'sendirinya',
 'seolah',
 'seolah-olah',
 'seorang',
 'sepanjang',
 'sepantasnya',
 'sepantasnyalah',
 'seperlunya',
 'seperti',
 'sepertinya',
 'sepihak',
 'sering',
 'seringnya',
 'serta',
 'serupa',
 'sesaat',
 'sesama',
 'sesampai',
 'sesegera',
 'sesekali',
 'seseorang',
 'sesuatu',
 'sesuatunya',
 'sesudah',
 'sesudahnya',
 'setelah',
 'setempat',
 'setengah',
 'seterusnya',
 'setiap',
 'setiba',
 'setibanya',
 'setidak-tidaknya',
 'setidaknya',
 'setinggi',
 'seusai',
 'sewaktu',
 'siap',
 'siapa',
 'siapakah',
 'siapapun',
 'sini',
 'sinilah',
 'soal',
 'soalnya',
 'suatu',
 'sudah',
 'sudahkah',
 'sudahlah',
 'supaya',
 'tadi',
 'tadinya',
 'tahu',
 'tahun',
 'tak',
 'tambah',
 'tambahnya',
 'tampak',
 'tampaknya',
 'tandas',
 'tandasnya',
 'tanpa',
 'tanya',
 'tanyakan',
 'tanyanya',
 'tapi',
 'tegas',
 'tegasnya',
 'telah',
 'tempat',
 'tengah',
 'tentang',
 'tentu',
 'tentulah',
 'tentunya',
 'tepat',
 'terakhir',
 'terasa',
 'terbanyak',
 'terdahulu',
 'terdapat',
 'terdiri',
 'terhadap',
 'terhadapnya',
 'teringat',
 'teringat-ingat',
 'terjadi',
 'terjadilah',
 'terjadinya',
 'terkira',
 'terlalu',
 'terlebih',
 'terlihat',
 'termasuk',
 'ternyata',
 'tersampaikan',
 'tersebut',
 'tersebutlah',
 'tertentu',
 'tertuju',
 'terus',
 'terutama',
 'tetap',
 'tetapi',
 'tiap',
 'tiba',
 'tiba-tiba',
 'tidak',
 'tidakkah',
 'tidaklah',
 'tiga',
 'tinggi',
 'toh',
 'tunjuk',
 'turut',
 'tutur',
 'tuturnya',
 'ucap',
 'ucapnya',
 'ujar',
 'ujarnya',
 'umum',
 'umumnya',
 'ungkap',
 'ungkapnya',
 'untuk',
 'usah',
 'usai',
 'waduh',
 'wah',
 'wahai',
 'waktu',
 'waktunya',
 'walau',
 'walaupun',
 'wong',
 'yaitu',
 'yakin',
 'yakni',
 'yang']

In [61]:
# membuat fungsi stopword removal

# menambahkan kata ke dalam stopword
more_stopword = ['ya', 'iya', 'nih', 'mas', 'nah', 'piak', 'sih', 'nya', 'serta', 'untuk', 'oh', 'loh', 'mana', 'si', 'eh', 'ln']
stopwords_ind = stopwords_ind + more_stopword

# daftar kata yang tidak boleh dihapus meskipun ada di stopword
exception_words = ['tidak', 'enggak', 'nggak', 'belum']

def remove_stop_word(text):
    clean_words = []
    text = text.split()
    for word in text:
        # hanya hapus jika kata ada di stopword dan bukan exception
        if word not in stopwords_ind or word in exception_words:
            clean_words.append(word)
    return " ".join(clean_words)

In [62]:
raw_sample = data['teks'].iloc[6]
case_folding = casefolding(raw_sample)
word_normal = text_normalize(case_folding)
stopword_removal = remove_stop_word(word_normal)

print('Raw Data \t\t :', raw_sample)
print('Case Folding \t\t :', case_folding)
print('Word Normalize \t\t :',word_normal)
print('Stop Word Removal \t\t :', stopword_removal)

Raw Data 		 : mohon izin Pak yang terbaru peraturan direksi nomor 28 tahun 2023 kalau tidak salah Pak mohon maaf Pak, ini betul Pak nomor 28 tahun 2023 tanggal 5 September Pak oke Pak Ronald untuk surat panggilan surat panggilan 1 itu jaraknya berapa Pak? panggilan kedua
30 hari Pak belum baca semua Pak panjang banget panggilan 1 panggilan kedua mungkin nanti saya coba belum tau Pak untuk jarak panggilan 1, panggilan kedua
mohon izin, mohon maaf saya belum tau Pak tapi biasanya kalau, bukan biasanya, saya kalau ada apa namanya kegiatan P2TL begitu Pak, saya lebih banyak membaca langsung ke apa namanya peraturan direksinya karena kalau saya hafal nanti Pak saya takut lupa pembongkaran pembongkaran langsung panggilan 3
panggilan 3 itu pembongkaran langsung pemutusan sementara
pemutusan sementara
sudah waktu panggilan 1 sudah putus pembongkaran Rampung itu setelah pelanggan
tidak membayar tagihannya ada surat apa itu sebelumnya?
ada surat panggilan panggilan pertama kedua dan ketiga
ada lagi nggak? panggilan tiga langsung pembongkaran Rampung itu
mohon izin saya lupa Pak baca ya perdirinya ya siap Pak kalau ada nih segelnya segelnya dirusak mas ya bukan karena alam, termasuk pelanggaran berapa itu mas?
mohon izin Bapak segel ABP atau segel MCB Bapak MCB contohnya masuk pelanggaran satu
eh pelanggaran dua kalau karena korosi mana mas? kalau segel karena korosi itu
termasuk pelanggaran nggak? bukan Bapak gangguan Bapak mungkin lebih ke arah pemeliharaan karena bukan disebabkan oleh
pelanggan Bapak surat tugas pernah ada surat tugasnya nggak mas pada waktu P2L itu mas?
ada Bapak ada surat tugasdi berita acara nomor berita acara Bapak sama tanggal pemeriksaan terus juga data pelaksana pelaksana P2TL terus juga data pelanggannya dan juga data mendamping Bapak atau pihak yang berwenang yang mendampingi terus juga hasil temuan hasil pemeriksaan dan juga tanda tangan dari tim P2TL nya kemudian pelanggan maupun saksi-saksi
Case Folding 		 : mohon izin pak yang terbaru peraturan direksi nomor 28 tahun 2023 kalau tidak salah pak mohon maaf pak ini betul pak nomor 28 tahun 2023 tanggal 5 september pak oke pak ronald untuk surat panggilan surat panggilan 1 itu jaraknya berapa pak panggilan kedua
30 hari pak belum baca semua pak panjang banget panggilan 1 panggilan kedua mungkin nanti saya coba belum tau pak untuk jarak panggilan 1 panggilan kedua
mohon izin mohon maaf saya belum tau pak tapi biasanya kalau bukan biasanya saya kalau ada apa namanya kegiatan p2tl begitu pak saya lebih banyak membaca langsung ke apa namanya peraturan direksinya karena kalau saya hafal nanti pak saya takut lupa pembongkaran pembongkaran langsung panggilan 3
panggilan 3 itu pembongkaran langsung pemutusan sementara
pemutusan sementara
sudah waktu panggilan 1 sudah putus pembongkaran rampung itu setelah pelanggan
tidak membayar tagihannya ada surat apa itu sebelumnya
ada surat panggilan panggilan pertama kedua dan ketiga
ada lagi nggak panggilan tiga langsung pembongkaran rampung itu
mohon izin saya lupa pak baca ya perdirinya ya siap pak kalau ada nih segelnya segelnya dirusak mas ya bukan karena alam termasuk pelanggaran berapa itu mas
mohon izin bapak segel abp atau segel mcb bapak mcb contohnya masuk pelanggaran satu
eh pelanggaran dua kalau karena korosi mana mas kalau segel karena korosi itu
termasuk pelanggaran nggak bukan bapak gangguan bapak mungkin lebih ke arah pemeliharaan karena bukan disebabkan oleh
pelanggan bapak surat tugas pernah ada surat tugasnya nggak mas pada waktu p2l itu mas
ada bapak ada surat tugasdi berita acara nomor berita acara bapak sama tanggal pemeriksaan terus juga data pelaksana pelaksana p2tl terus juga data pelanggannya dan juga data mendamping bapak atau pihak yang berwenang yang mendampingi terus juga hasil temuan hasil pemeriksaan dan juga tanda tangan dari tim p2tl nya kemudian pelanggan maupun saksisaksi
Word Normalize 		 : mohon izin pak yang terbaru peraturan direksi nomor 28 tahun 2023 kalau tidak salah pak mohon maaf pak ini betul pak nomor 28 tahun 2023 tanggal 5 september pak oke pak ronald untuk surat panggilan surat panggilan 1 itu jaraknya berapa pak panggilan kedua 30 hari pak belum baca semua pak panjang banget panggilan 1 panggilan kedua mungkin nanti saya coba belum tau pak untuk jarak panggilan 1 panggilan kedua mohon izin mohon maaf saya belum tau pak tapi biasanya kalau bukan biasanya saya kalau ada apa namanya kegiatan p2tl begitu pak saya lebih banyak membaca langsung ke apa namanya peraturan direksinya karena kalau saya hafal nanti pak saya takut lupa pembongkaran pembongkaran langsung panggilan 3 panggilan 3 itu pembongkaran langsung pemutusan sementara pemutusan sementara sudah waktu panggilan 1 sudah putus pembongkaran rampung itu setelah pelanggan tidak membayar tagihannya ada surat apa itu sebelumnya ada surat panggilan panggilan pertama kedua dan ketiga ada lagi tidak panggilan tiga langsung pembongkaran rampung itu mohon izin saya lupa pak baca ya perdirinya ya siap pak kalau ada nih segelnya segelnya dirusak mas ya bukan karena alam termasuk pelanggaran berapa itu mas mohon izin bapak segel abp atau segel mcb bapak mcb contohnya masuk pelanggaran satu eh pelanggaran dua kalau karena korosi mana mas kalau segel karena korosi itu termasuk pelanggaran tidak bukan bapak gangguan bapak mungkin lebih ke arah pemeliharaan karena bukan disebabkan oleh pelanggan bapak surat tugas pernah ada surat tugasnya tidak mas pada waktu p2l itu mas ada bapak ada surat tugasdi berita acara nomor berita acara bapak sama tanggal pemeriksaan terus juga data pelaksana pelaksana p2tl terus juga data pelanggannya dan juga data mendamping bapak atau pihak yang berwenang yang mendampingi terus juga hasil temuan hasil pemeriksaan dan juga tanda tangan dari tim p2tl nya kemudian pelanggan maupun saksisaksi
Stop Word Removal 		 : mohon izin terbaru peraturan direksi nomor 28 2023 tidak salah mohon maaf nomor 28 2023 tanggal 5 september oke ronald surat panggilan surat panggilan 1 jaraknya panggilan 30 belum baca banget panggilan 1 panggilan coba belum tau jarak panggilan 1 panggilan mohon izin mohon maaf belum tau namanya kegiatan p2tl membaca langsung namanya peraturan direksinya hafal takut lupa pembongkaran pembongkaran langsung panggilan 3 panggilan 3 pembongkaran langsung pemutusan pemutusan panggilan 1 putus pembongkaran rampung pelanggan tidak membayar tagihannya surat surat panggilan panggilan ketiga tidak panggilan langsung pembongkaran rampung mohon izin lupa baca perdirinya segelnya segelnya dirusak alam pelanggaran mohon izin segel abp segel mcb mcb contohnya masuk pelanggaran pelanggaran korosi segel korosi pelanggaran tidak gangguan arah pemeliharaan disebabkan pelanggan surat tugas surat tugasnya tidak p2l surat tugasdi berita acara nomor berita acara tanggal pemeriksaan data pelaksana pelaksana p2tl data pelanggannya data mendamping berwenang mendampingi hasil temuan hasil pemeriksaan tanda tangan tim p2tl pelanggan saksisaksi

## STEMMING

In [63]:
!pip -q install sastrawi

[notice] A new release of pip is available: 25.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [64]:
# mengubah kata menjadi kata dasar
from Sastrawi.Stemmer.StemmerFactory import StemmerFactory

factory = StemmerFactory()
stemmer = factory.create_stemmer()

# membuat fungsi untuk stemming bahasa indonesia
def stemming(text):
    text = stemmer.stem(text)
    return text

In [65]:
raw_data = data['teks'].iloc[100]
case_folding = casefolding(raw_sample)
word_normal = text_normalize(case_folding)
stopword_removal = remove_stop_word(word_normal)
text_stemming = stemming(stopword_removal)

print('Raw Data \t\t :', raw_sample)
print('Case Folding \t\t :', case_folding)
print('Word Normalize \t\t :',word_normal)
print('Stop Word Removal \t\t :', stopword_removal)
print('Stemming \t\t :', text_stemming)

Raw Data 		 : mohon izin Pak yang terbaru peraturan direksi nomor 28 tahun 2023 kalau tidak salah Pak mohon maaf Pak, ini betul Pak nomor 28 tahun 2023 tanggal 5 September Pak oke Pak Ronald untuk surat panggilan surat panggilan 1 itu jaraknya berapa Pak? panggilan kedua
30 hari Pak belum baca semua Pak panjang banget panggilan 1 panggilan kedua mungkin nanti saya coba belum tau Pak untuk jarak panggilan 1, panggilan kedua
mohon izin, mohon maaf saya belum tau Pak tapi biasanya kalau, bukan biasanya, saya kalau ada apa namanya kegiatan P2TL begitu Pak, saya lebih banyak membaca langsung ke apa namanya peraturan direksinya karena kalau saya hafal nanti Pak saya takut lupa pembongkaran pembongkaran langsung panggilan 3
panggilan 3 itu pembongkaran langsung pemutusan sementara
pemutusan sementara
sudah waktu panggilan 1 sudah putus pembongkaran Rampung itu setelah pelanggan
tidak membayar tagihannya ada surat apa itu sebelumnya?
ada surat panggilan panggilan pertama kedua dan ketiga
ada lagi nggak? panggilan tiga langsung pembongkaran Rampung itu
mohon izin saya lupa Pak baca ya perdirinya ya siap Pak kalau ada nih segelnya segelnya dirusak mas ya bukan karena alam, termasuk pelanggaran berapa itu mas?
mohon izin Bapak segel ABP atau segel MCB Bapak MCB contohnya masuk pelanggaran satu
eh pelanggaran dua kalau karena korosi mana mas? kalau segel karena korosi itu
termasuk pelanggaran nggak? bukan Bapak gangguan Bapak mungkin lebih ke arah pemeliharaan karena bukan disebabkan oleh
pelanggan Bapak surat tugas pernah ada surat tugasnya nggak mas pada waktu P2L itu mas?
ada Bapak ada surat tugasdi berita acara nomor berita acara Bapak sama tanggal pemeriksaan terus juga data pelaksana pelaksana P2TL terus juga data pelanggannya dan juga data mendamping Bapak atau pihak yang berwenang yang mendampingi terus juga hasil temuan hasil pemeriksaan dan juga tanda tangan dari tim P2TL nya kemudian pelanggan maupun saksi-saksi
Case Folding 		 : mohon izin pak yang terbaru peraturan direksi nomor 28 tahun 2023 kalau tidak salah pak mohon maaf pak ini betul pak nomor 28 tahun 2023 tanggal 5 september pak oke pak ronald untuk surat panggilan surat panggilan 1 itu jaraknya berapa pak panggilan kedua
30 hari pak belum baca semua pak panjang banget panggilan 1 panggilan kedua mungkin nanti saya coba belum tau pak untuk jarak panggilan 1 panggilan kedua
mohon izin mohon maaf saya belum tau pak tapi biasanya kalau bukan biasanya saya kalau ada apa namanya kegiatan p2tl begitu pak saya lebih banyak membaca langsung ke apa namanya peraturan direksinya karena kalau saya hafal nanti pak saya takut lupa pembongkaran pembongkaran langsung panggilan 3
panggilan 3 itu pembongkaran langsung pemutusan sementara
pemutusan sementara
sudah waktu panggilan 1 sudah putus pembongkaran rampung itu setelah pelanggan
tidak membayar tagihannya ada surat apa itu sebelumnya
ada surat panggilan panggilan pertama kedua dan ketiga
ada lagi nggak panggilan tiga langsung pembongkaran rampung itu
mohon izin saya lupa pak baca ya perdirinya ya siap pak kalau ada nih segelnya segelnya dirusak mas ya bukan karena alam termasuk pelanggaran berapa itu mas
mohon izin bapak segel abp atau segel mcb bapak mcb contohnya masuk pelanggaran satu
eh pelanggaran dua kalau karena korosi mana mas kalau segel karena korosi itu
termasuk pelanggaran nggak bukan bapak gangguan bapak mungkin lebih ke arah pemeliharaan karena bukan disebabkan oleh
pelanggan bapak surat tugas pernah ada surat tugasnya nggak mas pada waktu p2l itu mas
ada bapak ada surat tugasdi berita acara nomor berita acara bapak sama tanggal pemeriksaan terus juga data pelaksana pelaksana p2tl terus juga data pelanggannya dan juga data mendamping bapak atau pihak yang berwenang yang mendampingi terus juga hasil temuan hasil pemeriksaan dan juga tanda tangan dari tim p2tl nya kemudian pelanggan maupun saksisaksi
Word Normalize 		 : mohon izin pak yang terbaru peraturan direksi nomor 28 tahun 2023 kalau tidak salah pak mohon maaf pak ini betul pak nomor 28 tahun 2023 tanggal 5 september pak oke pak ronald untuk surat panggilan surat panggilan 1 itu jaraknya berapa pak panggilan kedua 30 hari pak belum baca semua pak panjang banget panggilan 1 panggilan kedua mungkin nanti saya coba belum tau pak untuk jarak panggilan 1 panggilan kedua mohon izin mohon maaf saya belum tau pak tapi biasanya kalau bukan biasanya saya kalau ada apa namanya kegiatan p2tl begitu pak saya lebih banyak membaca langsung ke apa namanya peraturan direksinya karena kalau saya hafal nanti pak saya takut lupa pembongkaran pembongkaran langsung panggilan 3 panggilan 3 itu pembongkaran langsung pemutusan sementara pemutusan sementara sudah waktu panggilan 1 sudah putus pembongkaran rampung itu setelah pelanggan tidak membayar tagihannya ada surat apa itu sebelumnya ada surat panggilan panggilan pertama kedua dan ketiga ada lagi tidak panggilan tiga langsung pembongkaran rampung itu mohon izin saya lupa pak baca ya perdirinya ya siap pak kalau ada nih segelnya segelnya dirusak mas ya bukan karena alam termasuk pelanggaran berapa itu mas mohon izin bapak segel abp atau segel mcb bapak mcb contohnya masuk pelanggaran satu eh pelanggaran dua kalau karena korosi mana mas kalau segel karena korosi itu termasuk pelanggaran tidak bukan bapak gangguan bapak mungkin lebih ke arah pemeliharaan karena bukan disebabkan oleh pelanggan bapak surat tugas pernah ada surat tugasnya tidak mas pada waktu p2l itu mas ada bapak ada surat tugasdi berita acara nomor berita acara bapak sama tanggal pemeriksaan terus juga data pelaksana pelaksana p2tl terus juga data pelanggannya dan juga data mendamping bapak atau pihak yang berwenang yang mendampingi terus juga hasil temuan hasil pemeriksaan dan juga tanda tangan dari tim p2tl nya kemudian pelanggan maupun saksisaksi
Stop Word Removal 		 : mohon izin terbaru peraturan direksi nomor 28 2023 tidak salah mohon maaf nomor 28 2023 tanggal 5 september oke ronald surat panggilan surat panggilan 1 jaraknya panggilan 30 belum baca banget panggilan 1 panggilan coba belum tau jarak panggilan 1 panggilan mohon izin mohon maaf belum tau namanya kegiatan p2tl membaca langsung namanya peraturan direksinya hafal takut lupa pembongkaran pembongkaran langsung panggilan 3 panggilan 3 pembongkaran langsung pemutusan pemutusan panggilan 1 putus pembongkaran rampung pelanggan tidak membayar tagihannya surat surat panggilan panggilan ketiga tidak panggilan langsung pembongkaran rampung mohon izin lupa baca perdirinya segelnya segelnya dirusak alam pelanggaran mohon izin segel abp segel mcb mcb contohnya masuk pelanggaran pelanggaran korosi segel korosi pelanggaran tidak gangguan arah pemeliharaan disebabkan pelanggan surat tugas surat tugasnya tidak p2l surat tugasdi berita acara nomor berita acara tanggal pemeriksaan data pelaksana pelaksana p2tl data pelanggannya data mendamping berwenang mendampingi hasil temuan hasil pemeriksaan tanda tangan tim p2tl pelanggan saksisaksi
Stemming 		 : mohon izin baru atur direksi nomor 28 2023 tidak salah mohon maaf nomor 28 2023 tanggal 5 september oke ronald surat panggil surat panggil 1 jarak panggil 30 belum baca banget panggil 1 panggil coba belum tau jarak panggil 1 panggil mohon izin mohon maaf belum tau nama giat p2tl baca langsung nama atur direksi hafal takut lupa bongkar bongkar langsung panggil 3 panggil 3 bongkar langsung putus putus panggil 1 putus bongkar rampung langgan tidak bayar tagih surat surat panggil panggil tiga tidak panggil langsung bongkar rampung mohon izin lupa baca diri segel segel rusak alam langgar mohon izin segel abp segel mcb mcb contoh masuk langgar langgar korosi segel korosi langgar tidak ganggu arah pelihara sebab langgan surat tugas surat tugas tidak p2l surat tugasdi berita acara nomor berita acara tanggal periksa data laksana laksana p2tl data langgan data damping wenang damping hasil temu hasil periksa tanda tangan tim p2tl langgan saksisaksi

## TEXT PREPROCESSING PIPELINE

In [66]:
# membuat fungsi untuk menghubungkan seluruh langkah text preprocessing
def text_preprocessing_process(text):
    text = casefolding(text)
    text = text_normalize(text)
    text = remove_stop_word(text)
    text = stemming(text)
    return text

In [67]:
%%time
data['clean_teks'] = data['teks'].apply(text_preprocessing_process)

CPU times: total: 8min 7s
Wall time: 8min 10s

In [68]:
data

,teks,label,clean_teks
0,"iya siap pak, masih masih di situ Pak surat pe...",0,situ surat tugas isi berita acara belum isi la...
1,"siap, siap Pak, hari ini saya lengkapi foto be...",0,lengkap foto belum kancing 028 028 2023 2023 j...
2,"izin Pak, untuk sekarang saya di bagian pelaya...",0,izin layan langgan surat tidak tetap transaksi...
3,iya administrasi Pak tapi posisinya sudah tida...,1,administrasi posisi tidak tangan p2tl join tau...
4,ini level 2 kalau nggak salah Pak petugas lapa...,1,level 2 tidak salah tugas lapang dokumen krusi...
...,...,...,...
291,"S1, Pak. Untuk sekarang karena sudah MULP, jad...",1,s1 mulp temu temanteman lapang administrasi ko...
292,Dari SMK Pak. Gimana Pak? Kalau saya Ibu melak...,1,smk p2tl surat tugas surat tugas bukti berita ...
293,"Masih, Pak. Ini untuk sebagai penanggung jawab...",1,tanggung butuh benarbenar oke bu langgan berat...
294,"Tadi sertifikasi kompetensi, surat tugas, sura...",1,sertifikasi kompetensi surat tugas surat kekat...
295,"Terus fakta integritas Oke, sudah benar. Pada ...",1,fakta integritas oke p2tl surat tugas kirim su...

In [69]:
# simpan data yang sudah dilakukan preprocessing ke dalam file csv
data.to_csv('clean_data_asesmen.csv')

## FEATURE ENGINEERING

In [70]:
# pisahkan kolom feature dan target
x = data['clean_teks']
y = data['label']

In [71]:
x

0      situ surat tugas isi berita acara belum isi la...
1      lengkap foto belum kancing 028 028 2023 2023 j...
2      izin layan langgan surat tidak tetap transaksi...
3      administrasi posisi tidak tangan p2tl join tau...
4      level 2 tidak salah tugas lapang dokumen krusi...
                             ...
291    s1 mulp temu temanteman lapang administrasi ko...
292    smk p2tl surat tugas surat tugas bukti berita ...
293    tanggung butuh benarbenar oke bu langgan berat...
294    sertifikasi kompetensi surat tugas surat kekat...
295    fakta integritas oke p2tl surat tugas kirim su...
Name: clean_teks, Length: 296, dtype: object

In [72]:
y

0      0
1      0
2      0
3      1
4      1
      ..
291    1
292    1
293    1
294    1
295    1
Name: label, Length: 296, dtype: int64

## FEATURE EXTRACTION MENGGUNAKAN TF-IDF DAN N-GRAM

In [73]:
# save model
import pickle

#TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer

# Unigram
vec_TF_IDF = TfidfVectorizer(ngram_range=(1,2))
vec_TF_IDF.fit(x)

x_tf_idf = vec_TF_IDF.transform(x)

pickle.dump(vec_TF_IDF,open("feature_tf-idf_asesmen.pkl", "wb"))

In [74]:
# menampilkan vocabulary dari TF-IDF
vec_TF_IDF.vocabulary_

{'situ': 17656,
 'surat': 18168,
 'tugas': 20294,
 'isi': 7235,
 'berita': 3294,
 'acara': 707,
 'belum': 3031,
 'langsung': 10325,
 'ini': 7111,
 'meriksa': 12105,
 'dokumen': 5353,
 'dokumendokumen': 5383,
 'ba': 2305,
 'izin': 7327,
 'masuk': 11715,
 'lokasi': 11260,
 'langgar': 10194,
 'temu': 18972,
 'hasil': 6544,
 'periksa': 14892,
 'langgan': 9860,
 'datang': 4802,
 'selesai': 17032,
 'kantor': 8111,
 'bawa': 2759,
 'serah': 17183,
 'administrasi': 905,
 'banya': 2610,
 'barang': 2643,
 'bukti': 3835,
 'lapang': 10465,
 'segel': 16874,
 'rusak': 16419,
 'gantung': 6254,
 'posisi': 15519,
 'mcb': 11879,
 'b1': 2241,
 'level': 10933,
 'laksana': 9660,
 'cari': 4063,
 'kali': 8011,
 'tidak': 19419,
 'hitung': 6687,
 'nama': 12531,
 'ketemu': 8818,
 'bagi': 2455,
 'teman': 18877,
 'khusus': 8866,
 'penting': 14717,
 'sma': 17798,
 'terima': 19215,
 'baru': 2666,
 'alam': 1114,
 'jenis': 7647,
 'situ surat': 17731,
 'surat tugas': 18214,
 'tugas isi': 20360,
 'isi berita': 7245,
 'berita acara': 3296,
 'acara belum': 724,
 'belum isi': 3057,
 'isi langsung': 7259,
 'langsung ini': 10369,
 'ini meriksa': 7118,
 'meriksa dokumen': 12106,
 'dokumen situ': 5376,
 'situ berita': 17670,
 'acara dokumendokumen': 739,
 'dokumendokumen ba': 5384,
 'ba ba': 2311,
 'ba surat': 2340,
 'surat izin': 18185,
 'izin masuk': 7363,
 'masuk lokasi': 11771,
 'lokasi langgar': 11279,
 'langgar temu': 10306,
 'temu langgar': 19025,
 'langgar hasil': 10228,
 'hasil temu': 6604,
 'temu hasil': 19001,
 'hasil periksa': 6594,
 'periksa langgan': 14976,
 'langgan datang': 9940,
 'datang langgan': 4806,
 'langgan selesai': 10134,
 'selesai langgan': 17052,
 'langgan kantor': 9993,
 'kantor selesai': 8169,
 'selesai bawa': 17034,
 'bawa berita': 2765,
 'acara serah': 819,
 'serah administrasi': 17184,
 'administrasi banya': 915,
 'banya barang': 2611,
 'barang bukti': 2646,
 'bukti temu': 3924,
 'temu temu': 19071,
 'temu lapang': 19027,
 'lapang segel': 10566,
 'segel rusak': 16910,
 'rusak gantung': 16426,
 'gantung posisi': 6272,
 'posisi periksa': 15535,
 'periksa segel': 15024,
 'rusak mcb': 16432,
 'mcb b1': 11884,
 'b1 level': 2250,
 'level laksana': 10965,
 'laksana lapang': 9709,
 'lapang cari': 10492,
 'cari kali': 4073,
 'kali tidak': 8063,
 'tidak hitung': 19523,
 'hitung kali': 6703,
 'kali surat': 8059,
 'lokasi nama': 11285,
 'nama hasil': 12565,
 'hasil ketemu': 6578,
 'ketemu temu': 8835,
 'lapang bagi': 10484,
 'bagi periksa': 2458,
 'periksa teman': 15045,
 'teman khusus': 18883,
 'khusus isi': 8872,
 'acara penting': 799,
 'penting hasil': 14719,
 'temu sma': 19066,
 'sma terima': 17813,
 'terima sma': 19237,
 'sma baru': 17800,
 'baru belum': 2674,
 'belum belum': 3042,
 'belum alam': 3034,
 'alam gantung': 1120,
 'posisi belum': 15522,
 'belum temu': 3121,
 'temu tidak': 19073,
 'tidak jenis': 19549,
 'lengkap': 10810,
 'foto': 6146,
 'kancing': 8106,
 '028': 90,
 '2023': 425,
 'juni': 7735,
 'data': 4699,
 'huni': 6809,
 'tarif': 18679,
 'daya': 4812,
 'alamat': 1148,
 'tanda': 18497,
 'tangan': 18521,
 'saksi': 16548,
 'contoh': 4312,
 'besar': 3371,
 'batas': 2707,
 'kategori': 8294,
 'maaf': 11398,
 'lupa': 11347,
 'p1': 13305,
 'baca': 2353,
 'p2': 13390,
 'admin': 894,
 'temanteman': 18889,
 'simpan': 17504,
 'tetap': 19321,
 'ap2t': 1748,
 'sesuai': 17307,
 'jurnis': 7743,
 'maksud': 11545,
 'panggil': 14081,
 'buat': 3769,
 'jarak': 7556,
 'tiga': 19775,
 'paham': 13894,
 'dasar': 4621,
 'piak': 15205,
 'lengkap foto': 10835,
 'foto belum': 6149,
 'belum kancing': 3062,
 'kancing 028': 8107,
 '028 028': 91,
 '028 2023': 95,
 '2023 2023': 430,
 '2023 juni': 449,
 'juni juni': 7737,
 'juni 2023': 7736,
 '2023 situ': 486,
 'situ isi': 17687,
 'isi data': 7249,
 'data langgan': 4738,
 'langgan data': 9938,
 'langgan huni': 9970,
 'huni tarif': 6812,
 'tarif daya': 18684,
 'daya alamat': 4819,
 'alamat tugas': 1158,
 'tugas periksa': 20415,
 'periksa jenis': 14956,
 'jenis temu': 7663,
 'temu tanda': 19067,
 'tanda tangan': 18500,
 'tangan langgan': 18536,
 'langgan saksi': 10126,
 'saksi tugas': 16575,
 'tugas contoh': 20333,
 'contoh besar': 4318,
 'besar batas': 3376,
 'batas masuk': 2732,
 'masuk langgar': 11764,
 'langgar kategori': 10241,
 'kategori langgar': 8308,
 'langgar besar': 10216,
 'besar daya': 3380,
 'daya maaf': 4862,
 'maaf lupa': 11413,
 'lupa p1': 11375,
 'p1 baca': 13309,
 'baca 028': 2355,
 '028 p2': 154,
 'p2 maaf': 13421,
 'lupa admin': 11349,
 'admin terima': 902,
 'terima berita': 19219,
 'acara hasil': 748,
 'periksa temanteman': 15046,
 'temanteman lapang': 18914,
 'lapang simpan': 10572,
 'simpan dokumen': 17505,
 'dokumen hasil': 5362,
 'periksa periksa': 15013,
 'periksa barang': 14912,
 'bukti bawa': 3849,
 'bawa temanteman': 2798,
 'temanteman nama': 18918,
 'nama dokumen': 12556,
 'dokumen tetap': 5381,
 'tetap ap2t': 19324,
 'ap2t sesuai': 1761,
 'sesuai jurnis': 17349,
 'jurnis langgar': 7744,
 'langgar maksud': 10265,
 'maksud surat': 11589,
 'surat panggil': 18198,
 'panggil surat': 14165,
 'panggil berita': 14096,
 'acara langgan': 766,
 'langgan tidak': 10173,
 'tidak langgan': 19584,
 'langgan panggil': 10076,
 'panggil panggil': 14150,
 'acara berita': 725,
 'acara tugas': 846,
 'tugas lapang': 20383,
 'lapang temanteman': 10585,
 'lapang panggil': 10551,
 'panggil tidak': 14176,
 'tidak buat': 19470,
 'buat panggil': 3781,
 'panggil jarak': 14121,
 'jarak panggil': 7562,
 'tidak panggil': 19650,
 'panggil tiga': 14177,
 'tiga panggil': 19812,
 'tiga tidak': 19824,
 'tidak belum': 19456,
 'belum baca': 3037,
 'baca tidak': 2435,
 'tidak paham': 19648,
 'paham tetap': 13912,
 'tetap dasar': 19331,
 'dasar berita': 4630,
 'tidak tidak': 19746,
 'buat tetap': 3788,
 'tetap piak': 19363,
 'piak panggil': 15206,
 'layan': 10661,
 'transaksi': 20211,
 'energi': 5611,
 'p2tl': 13486,
 'maret': 11688,
 'kemarin': 8518,
 'enggak': 5665,
 'murni': 12487,
 'melobby': 12014,
 'komplain': 9032,
 'bantu': 2593,
 'media': 11986,
 'halo': 6490,
 'hadir': 6452,
 'kirim': 8932,
 'terus': 19283,
 'minggu': 12300,
 'ikut': 6877,
 'perdir': 14781,
 '88': 664,
 'jadwal': 7447,
 'lihat': 11073,
 'nomor': 12810,
 'tanggal': 18572,
 'serta': 17239,
 'jabat': 7390,
 'sambung': 16690,
 'untuk': 20979,
 'ambil': 1355,
 'meter': 12127,
 'kwh': 9422,
 'tim': 19832,
 'ketua': 8850,
 'sidik': 17465,
 'app': 1900,
 'merek': 12101,
 'putar': 15792,
 'pasang': 14347,
 'kotak': 9282,
 'simpul': 17517,
 'tindak': 19916,
 'sengaja': 17136,
 'tau': 18701,
 'izin layan': 7358,
 'layan langgan': 10669,
 'langgan surat': 10150,
 'surat tidak': 18211,
 'tidak tetap': 19745,
 'tetap transaksi': 19383,
 'transaksi energi': 20214,
 'energi p2tl': 5643,
 'p2tl maret': 13622,
 'maret kemarin': 11691,
 'kemarin surat': 8572,
 'tugas enggak': 20344,
 'enggak surat': 5800,
 'tugas foto': 20346,
 'foto tetap': 6160,
 'tetap murni': 19354,
 'murni transaksi': 12488,
 'energi layan': 5634,
 'langgan melobby': 10042,
 'melobby langgan': 12015,
 'langgan langgan': 10020,
 'langgan komplain': 10007,
 'komplain bantu': 9033,
 'bantu media': 2600,
 'media tetap': 11989,
 'tetap halo': 19335,
 'halo halo': 6491,
 'halo tidak': 6497,
 'tidak hadir': 19517,
 'hadir kali': 6453,
 'kali panggil': 8052,
 'panggil kirim': 14133,
 'kirim surat': 8944,
 'panggil enggak': 14110,
 'enggak terus': 5811,
 'terus surat': 19286,
 'jarak jarak': 7559,
 'jarak minggu': 7561,
 'minggu ikut': 12306,
 'ikut perdir': 6889,
 'perdir 88': 14797,
 '88 perdir': 668,
 'perdir belum': 14807,
 'belum panggil': 3092,
 'enggak masuk': 5751,
 'masuk panggil': 11783,
 'tiga jadwal': 19793,
 'jadwal minggu': 7453,
 'minggu perdir': 12311,
 'belum surat': 3115,
 'surat ba': 18171,
 'ba lihat': 2331,
 'lihat nomor': 11113,
 'nomor surat': 12843,
 'surat tanggal': 18206,
 'tanggal nama': 18578,
 'nama nama': 12581,
 'nama langgan': 12573,
 'langgan nama': 10051,
 'nama tugas': 12613,
 'tugas serta': 20431,
 'serta jabat': 17247,
 'jabat nama': 7402,
 'nama alamat': 12534,
 'alamat langgan': 1153,
 'langgan sambung': 10128,
 'sambung untuk': 16721,
 'untuk data': 20982,
 'data barang': 4709,
 'bukti ambil': 3841,
 'ambil isi': 1373,
 'isi meter': 7265,
 'meter kwh': 12178,
 'kwh tim': 9472,
 'tim p2tl': 19874,
 'p2tl ketua': 13599,
 'ketua tugas': 8856,
 'tugas sidik': 20436,
 'sidik saksi': 17476,
 'saksi periksa': 16567,
 'periksa app': 14905,
 'app periksa': 1929,
 'app data': 1910,
 'data kwh': 4731,
 'kwh merek': 9449,
 'merek putar': 12103,
 'putar segel': 15807,
 'segel pasang': 16905,
 'pasang batas': 14350,
 'batas kotak': 2726,
 'kotak app': 9283,
 'app simpul': 1933,
 'simpul hasil': 17523,
 'periksa tindak': 15055,
 'tindak segel': 19934,
 'rusak masuk': 16431,
 'langgar p2': 10273,
 'p2 rusak': 13440,
 'rusak rusak': 16436,
 'rusak sengaja': 16438,
 'sengaja belum': 17137,
 'belum p2': 3088,
 'p2 tau': 13447,
 'tau p2tl': 18710,
 'p2tl p2tl': 13636,
 'p2tl ikut': 13574,
 'ikut 2023': 6879,
 '2023 belum': 436,
 'belum tau': 3119,
 'join': 7684,
 'balancenya': 2511,
 'dinamis': 5149,
 'tibatiba': 19409,
 'mutasi': 12491,
 'upload': 21042,
 'pindah': 15230,
 'sales': 16671,
 'retail': 16195,
 'coba': 4281,
 'caricari': 4087,
 'panjang': 14188,
 'insya': 7192,
 'allah': 1290,
 'bidang': 3449,
 'pakai': 13914,
 'salah': 16582,
 'perdirnya': 14842,
 'ingat': 7040,
 'terbit': 19190,
 'jangka': 7532,
 'bongkar': 3603,
 'habis': 6413,
 'administrasi posisi': 960,
 'posisi tidak': 15540,
 'tidak tangan': 19732,
 'tangan p2tl': 18540,
 'p2tl join': 13584,
 'join tau': 7685,
 'tau balancenya': 18702,
 'balancenya dinamis': 2512,
 'dinamis tidak': 5150,
 'tidak tau': 19736,
 'tau tibatiba': 18711,
 'tibatiba mutasi': 19414,
 'mutasi upload': 12506,
 'upload 2023': 21043,
 '2023 pindah': 479,
 'pindah sales': 15246,
 'sales retail': 16673,
 'retail coba': 16196,
 'coba izin': 4294,
 'izin caricari': 7340,
 'caricari panjang': 4088,
 'panjang administrasi': 14189,
 'administrasi perdir': 958,
 'perdir 028': 14786,
 '028 perdir': 158,
 '028 insya': 128,
 'insya allah': 7193,
 'allah pindah': 1294,
 'pindah pindah': 15243,
 'pindah bidang': 15231,
 'bidang baca': 3450,
 'baca pakai': 2414,
 'pakai 2023': 13919,
 '2023 tidak': 495,
 'tidak salah': 19697,
 'salah perdirnya': 16651,
 'perdirnya surat': 14861,
 'panggil ingat': 14117,
 'ingat terbit': 7101,
 'terbit jangka': 19195,
 'jangka ingat': 7535,
 'terbit tidak': 19203,
 'langgan terbit': 10165,
 'terbit ingat': 19194,
 'ingat ingat': 7062,
 'ingat tidak': 7105,
 'tidak bongkar': 19467,
 'bongkar tidak': 3652,
 'tidak ingat': 19532,
 'ingat bongkar': 7050,
 'bongkar ingat': 3617,
 'ingat habis': 7060,
 'habis jangka': 6427,
 'jangka langsung': 7539,
 'langsung tugas': 10439,
 'tugas bongkar': 20329,
 'ingat 028': 7041,
 '028 nama': 148,
 'nama barang': 12544,
 'bukti tau': 3922,
 'tau dokumen': 18704,
 'barang hasil': 2648,
 'periksa nama': 14995,
 'krusial': 9317,
 'wajib': 21216,
 'wpjsa': 21325,
 'kerja': 8677,
 'ranah': 15973,
 'hukum': 6766,
 'sertifikasi': 17256,
 'mesti': 12117,
 'pulang': 15750,
 'jsa': 7696,
 'akal': 1054,
 'banding': 2560,
 'formulir': 6144,
 'label': 9548,
 'ktp': 9325,
 'menandatangani': 12027,
 'tulis': 20525,
 'spesifikasi': 17927,
 'kenal': 8626,
 'oke': 13053,
 'berkas': 3311,
 'manusia': 11667,
 'kak': 7996,
 'lain': 9579,
 'banget': 2581,
 'lampu': 9847,
 'aman': 1310,
 'salak': 16669,
 'kecuali': 8446,
 'alat': 1169,
 'ukur': 20700,
 'maksa': 11509,
 'lampung': 9852,
 'lanjut': 10447,
 'tagih': 18383,
 'bayar': 2814,
 'susul': 18249,
 'level tidak': 10999,
 'salah tugas': 16665,
 'lapang dokumen': 10502,
 'dokumen krusial': 5366,
 'krusial wajib': 9318,
 'wajib wajib': 21244,
 'wajib surat': 21238,
 'tugas wpjsa': 20465,
 'wpjsa izin': 21326,
 'izin kerja': 7351,
 'kerja masuk': 8726,
 'masuk ranah': 11795,
 'ranah hukum': 15974,
 'hukum masuk': 6781,
 'hukum sertifikasi': 6796,
 'sertifikasi mesti': 17265,
 'mesti pulang': 12120,
 'pulang maksud': 15752,
 'maksud dokumen': 11555,
 'dokumen p2tl': 5373,
 'p2tl surat': 13685,
 'tugas jsa': 20363,
 'jsa izin': 7702,
 'kerja berita': 8691,
 'acara tidak': 841,
 'tidak berita': 19461,
 'tidak p2tl': 19645,
 'p2tl tidak': 13701,
 'tidak surat': 19724,
 'tugas akal': 20297,
 'akal berita': 1055,
 'acara pulang': 807,
 'pulang langgan': 15751,
 'langgan banding': 9898,
 'banding p2tl': 2577,
 'p2tl formulir': 13564,
 'formulir berita': 6145,
 'acara isi': 755,
 'isi lengkap': 7262,
 'lengkap isi': 10841,
 'lengkap label': 10851,
 'label nama': 9549,
 'langgan ktp': 10013,
 'ktp langgan': 9327,
 'langgan menandatangani': 10043,
 'menandatangani hasil': 12030,
 'temu tulis': 19078,
 'tulis sesuai': 20545,
 'sesuai temu': 17387,
 'temu data': 18993,
 'data data': 4713,
 'data spesifikasi': 4767,
 'spesifikasi meter': 17929,
 'meter data': 12153,
 'data kenal': 4727,
 'kenal meter': 8631,
 'meter oke': 12198,
 'oke serah': 13129,
 'serah serah': 17197,
 'serah berkas': 17188,
 'berkas barang': 3316,
 'periksa perdir': 15011,
 'perdir nomor': 14818,
 'nomor 028': 12813,
 '028 app': 99,
 'app rusak': 1932,
 'rusak alam': 16420,
 'alam manusia': 1132,
 'manusia kategori': 11675,
 'kategori alam': 8295,
 'alam kategori': 1124,
 'kategori p1': 8313,
 'p1 p1': 13352,
 'p1 rusak': 13366,
 'manusia kak': 11674,
 'kak lain': 7997,
 'lain lain': 9610,
 'lain nomor': 9618,
 'nomor lain': 12832,
 'lain banget': 9586,
 'banget bongkar': 2583,
 'bongkar lampu': 3627,
 'lampu langgan': 9850,
 'langgan bongkar': 9922,
 'lampu app': 9848,
 'app aman': 1902,
 'aman p2tl': 1334,
 'tidak salak': 19698,
 'salak lokasi': 16670,
 'lokasi kecuali': 11275,
 'kecuali layan': 8456,
 'layan langgar': 10670,
 'langgar aman': 10200,
 'aman alat': 1311,
 'alat alat': 1172,
 'alat ukur': 1245,
 'ukur maksa': 20780,
 'maksa bongkar': 11510,
 'bongkar lampung': 3628,
 'lampung masuk': 9855,
 'masuk lanjut': 11765,
 'lanjut administrasi': 10448,
 'administrasi surat': 969,
 'surat tagih': 18205,
 'tagih layan': 18395,
 'langgan layan': 10026,
 'langgan pasang': 10082,
 'pasang pasang': 14374,
 'pasang bayar': 14351,
 'bayar tagih': 2863,
 'tagih susul': 18407,
 'susul tetap': 18292,
 'tetap oke': 19357,
 'utama': 21080,
 'mbak': 11863,
 'seharihari': 16937,
 'mana': 11613,
 'koordinator': 9216,
 'membackup': 12016,
 'frontliner': 6168,
 'ts': 20237,
 'skd': 17773,
 'bongkarampung': 3653,
 'gulung': 6400,
 'kabel': 7807,
 'tiang': 19396,
 'tempat': 18945,
 'pagi': 13888,
 'briefing': 3676,
 'k1': 7755,
 'koordinernya': 9223,
 'tandatangan': 18502,
 'polisi': 15450,
 'kena': 8596,
 'bbnya': 2889,
 'potong': 15563,
 'komplit': 9034,
 'coret': 4362,
 'ulpnya': 20924,
 'mohon': 12404,
 'kasih': 8235,
 'uang': 20631,
 'akibat': 1063,
 'pelagaran': 14557,
 'id': 6830,
 'rumah': 16321,
 'sekiansekian': 16989,
 'pengkarampung': 14708,
 'nikmat': 12788,
 'listrik': 11163,
 'laksana utama': 9764,
 'utama mbak': 21092,
 'mbak laksana': 11866,
 'laksana seharihari': 9745,
 'seharihari mana': 16951,
 'mana mbak': 11618,
 'mbak seharihari': 11871,
 'seharihari laksana': 16947,
 'utama seharihari': 21098,
 'seharihari koordinator': 16946,
 'koordinator koordinator': 9217,
 'koordinator tim': 9221,
 'tim membackup': 19868,
 'membackup frontliner': 12017,
 'frontliner langgan': 6169,
 'selesai ts': 17080,
 'ts p2tl': 20246,
 'p2tl lapang': 13611,
 'lapang mbak': 10537,
 'mbak lapang': 11868,
 'lapang kantor': 10517,
 'kantor skd': 8172,
 'skd 028': 17774,
 '028 panggil': 156,
 'acara surat': 829,
 'surat ingat': 18183,
 'ingat surat': 7096,
 'ingat bongkarampung': 7051,
 'bongkarampung gulung': 3656,
 'gulung kabel': 6401,
 'kabel tiang': 7832,
 'tiang surat': 19404,
 'tugas tidak': 20453,
 'tidak mbak': 19605,
 'mbak surat': 11873,
 'tugas laksana': 20377,
 'laksana laksana': 9704,
 'laksana tempat': 9756,
 'tempat pagi': 18947,
 'pagi briefing': 13890,
 'briefing briefing': 3679,
 'briefing tim': 3688,
 'tim surat': 19888,
 'tugas lain': 20375,
 'lain k1': 9603,
 'k1 k1': 7756,
 'k1 mana': 7757,
 'mana lain': 11616,
 'lain segel': 9627,
 'segel p2': 16904,
 'p2 periksa': 13437,
 'periksa tanggal': 15043,
 'tanggal tim': 18583,
 'tim laksana': 19862,
 'laksana koordinernya': 9702,
 'koordinernya tandatangan': 9224,
 'tandatangan polisi': 18503,
 'polisi data': 15457,
 'data lengkap': 4743,
 'lengkap langgan': 10854,
 'datang kena': 4805,
 'kena p2tl': 8610,
 'p2tl lain': 13604,
 'lain langgar': 9613,
 'langgar isi': 10231,
 'isi bbnya': 7243,
 'bbnya mcb': 2891,
 'mcb kwh': 11903,
 'kwh kabel': 9433,
 'kabel meter': 7824,
 'meter potong': 12213,
 'potong komplit': 15565,
 'komplit komplit': 9035,
 'komplit tidak': 9037,
 'tidak coret': 19483,
 'coret tagih': 4364,
 'susul ba': 18256,
 'ba administrasi': 2306,
 'administrasi langsung': 937,
 'langsung mbak': 10394,
 'mbak admin': 11864,
 'admin langgan': 897,
 'kantor tagih': 8177,
 'susul ulpnya': 18296,
 'ulpnya langgan': 20925,
 'selesai tagih': 17072,
 'susul tagih': 18289,
 'susul serta': 18285,
 'serta surat': 17255,
 'ingat isi': 7063,
 'isi mbak': 7264,
 'ingat mbak': 7083,
 'ingat laksana': 7075,
 'laksana surat': 9752,
 'panggil mohon': 14143,
 'mohon selesai': 12413,
 'susul p2tl': 18280,
 'tidak kasih': 19554,
 'kasih tau': 8268,
 'tau uang': 18713,
 'uang ingat': 20635,
 'ingat selesai': 7093,
 'susul akibat': 18254,
 'akibat pelagaran': 1067,
 'pelagaran id': 14558,
 'id rumah': 6835,
 'rumah sekiansekian': 16365,
 'sekiansekian mohon': 16991,
 'mohon kantor': 12409,
 'kantor tidak': 8181,
 'tidak kantor': 19553,
 'kantor kirim': 8143,
 'panggil pengkarampung': 14153,
 'pengkarampung surat': 14710,
 'ingat pengkarampung': 7087,
 'pengkarampung pasang': 14709,
 'pasang mbak': 14369,
 'mbak langgan': 11867,
 'langgan nikmat': 10058,
 'nikmat listrik': 12789,
 'listrik mbak': 11203,
 'mbak selesai': 11872,
 'susul langsung': 18271,
 'langsung pasang': 10404,
 'atur': 2136,
 'direksi': 5177,
 '28': 545,
 'september': 17174,
 'ronald': 16248,
 '30': 569,
 'giat': 6317,
 'hafal': 6460,
 'takut': 18465,
 'putus': 15821,
 'rampung': 15911,
 'diri': 5190,
 'abp': 692,
 'korosi': 9238,
 'ganggu': 6216,
 'arah': 1983,
 'pelihara': 14601,
 'sebab': 16831,
 'p2l': 13467,
 'tugasdi': 20468,
 'damping': 4553,
 'wenang': 21266,
 'saksisaksi': 16578,
 'mohon izin': 12408,
 'izin baru': 7334,
 'baru atur': 2673,
 'atur direksi': 2145,
 'direksi nomor': 5184,
 'nomor 28': 12817,
 '28 2023': 548,
 'salah mohon': 16638,
 'mohon maaf': 12410,
 'maaf nomor': 11415,
 '2023 tanggal': 491,
 'tanggal september': 18581,
 'september oke': 17176,
 'oke ronald': 13123,
 'ronald surat': 16249,
 'panggil 30': 14085,
 '30 belum': 574,
 'baca banget': 2366,
 'banget panggil': 2584,
 'panggil coba': 14105,
 'coba belum': 4284,
 'tau jarak': 18705,
 'izin mohon': 7365,
 'maaf belum': 11404,
 'tau nama': 18708,
 'nama giat': 12561,
 'giat p2tl': 6322,
 'p2tl baca': 13518,
 'baca langsung': 2406,
 'langsung nama': 10395,
 'nama atur': 12540,
 'direksi hafal': 5183,
 'hafal takut': 6464,
 'takut lupa': 18469,
 'lupa bongkar': 11358,
 'bongkar bongkar': 3613,
 'bongkar langsung': 3630,
 'langsung panggil': 10401,
 'panggil bongkar': 14098,
 'langsung putus': 10412,
 'putus putus': 15860,
 'putus panggil': 15855,
 'panggil putus': 14158,
 'putus bongkar': 15832,
 'bongkar rampung': 3639,
 'rampung langgan': 15943,
 'tidak bayar': 19454,
 'tagih surat': 18406,
 'surat surat': 18204,
 'panggil langsung': 14136,
 'langsung bongkar': 10345,
 'rampung mohon': 15950,
 'izin lupa': 7360,
 'lupa baca': 11355,
 'baca diri': 2382,
 'diri segel': 5198,
 'segel segel': 16912,
 'alam langgar': 1130,
 'langgar mohon': 10268,
 'izin segel': 7377,
 'segel abp': 16875,
 'abp segel': 695,
 'segel mcb': 16899,
 'mcb mcb': 11910,
 'mcb contoh': 11891,
 'contoh masuk': 4332,
 'langgar langgar': 10256,
 'langgar korosi': 10249,
 'korosi segel': 9247,
 'segel korosi': 16894,
 'korosi langgar': 9244,
 'langgar tidak': 10311,
 'tidak ganggu': 19511,
 'ganggu arah': 6217,
 'arah pelihara': 1997,
 'pelihara sebab': 14609,
 'sebab langgan': 16835,
 'tugas surat': 20442,
 'tidak p2l': 19643,

In [75]:
# melihat jumlah feature
print(len(vec_TF_IDF.get_feature_names_out()))

21356

In [76]:
# melihat fitur-fitur apa saja yang ada di dalam corpus
print(vec_TF_IDF.get_feature_names_out())

['00' '00 008' '0023' ... 'zoom' 'zp' 'zp dir']

In [77]:
x1 = vec_TF_IDF.transform(x).toarray()
data_tabular_tf_idf = pd.DataFrame(x1,columns=vec_TF_IDF.get_feature_names_out())
data_tabular_tf_idf

,00,00 008,0023,0023 0163,0023 perdir,0028,0028 0028,0028 2023,0028 app,0028 atur,...,yuk tetangga,yuk tidak,yuridiksi,yuridiksi ngerenah,zaman,zaman error,zaman tl,zoom,zp,zp dir
0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
292,0.0,0.0,0.0,0.0,0.0,0.047636,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
293,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
294,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
295,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [78]:
data_tabular_tf_idf.iloc[10:20,60:70]

,0028 tip,0028 titik,0028p,0028p langgan,007,007 dir,008,008 00,008 008,008 088
10,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
11,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
12,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
13,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
15,0.0,0.0,0.0,0.0,0.0,0.0,0.050407,0.0,0.0,0.0
16,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
17,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
18,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0
19,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0

## FEATURE SELECTION

In [79]:
x_train = np.array(data_tabular_tf_idf)
y_train = np.array(y)

In [81]:
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import chi2

chi2_feature = SelectKBest(chi2, k=10000)
x_kbest_features = chi2_feature.fit_transform(x_train, y_train)

# untuk reduce feature
print('original feature number', x_train.shape[1])
print('reduce feature number', x_kbest_features.shape[1])

original feature number 21356
reduce feature number 10000

In [83]:
Data = pd.DataFrame(chi2_feature.scores_,columns=['Nilai'])
Data

          Nilai
0      0.325768
1      0.325768
2      1.337499
3      0.668750
4      0.668750
...         ...
21351  0.012594
21352  0.019388
21353  0.251533
21354  0.605032
21355  0.605032

[21356 rows x 1 columns]

In [84]:
# menampilkan data feature beserta nilainya
feature = vec_TF_IDF.get_feature_names_out()
feature

Data['Fitur'] = feature
Data

          Nilai        Fitur
0      0.325768           00
1      0.325768       00 008
2      1.337499         0023
3      0.668750    0023 0163
4      0.668750  0023 perdir
...         ...          ...
21351  0.012594  zaman error
21352  0.019388     zaman tl
21353  0.251533         zoom
21354  0.605032           zp
21355  0.605032       zp dir

[21356 rows x 2 columns]

In [85]:
# mengurutkan nilai fitur terbaik
Data.sort_values(by='Nilai', ascending=False)

              Nilai          Fitur
193    9.783851e+00            088
14789  7.131900e+00     perdir 088
382    4.483731e+00           2016
196    3.859301e+00       088 2016
664    3.848017e+00             88
...             ...            ...
16487  7.565114e-07    sadap kabel
18058  7.050253e-07            stm
10965  5.169841e-07  level laksana
7562   2.120178e-07  jarak panggil
10893  3.015714e-08  lengkap tidak

[21356 rows x 2 columns]

In [86]:
mask = chi2_feature.get_support()
mask

array([ True,  True,  True, ...,  True,  True,  True], shape=(21356,))

In [87]:
# menampilkan fitur yang terpilih berdasarkan nilai mask atau nilai tertinggi yang sudah ditetapkan pada chi square
new_feature=[]
for bool, f in zip(mask, feature):
    if bool :
        new_feature.append(f)
    selected_feature = new_feature
selected_feature

['00',
 '00 008',
 '0023',
 '0023 0163',
 '0023 perdir',
 '0028',
 '0028 0028',
 '0028 2023',
 '0028 app',
 '0028 baca',
 '0028 baru',
 '0028 belum',
 '0028 damping',
 '0028 dokumen',
 '0028 garing',
 '0028 izin',
 '0028 jenis',
 '0028 kait',
 '0028 kompetensi',
 '0028 lain',
 '0028 laku',
 '0028 langgan',
 '0028 langgar',
 '0028 lengkap',
 '0028 masingmasing',
 '0028 masuk',
 '0028 mbak',
 '0028 mengevolasi',
 '0028 nonpelanggan',
 '0028 oke',
 '0028 organisasi',
 '0028 p2tl',
 '0028 panggil',
 '0028 perdir',
 '0028 sementara',
 '0028 serahin',
 '0028 sesuai',
 '0028 tanda',
 '0028 tip',
 '0028 titik',
 '0028p',
 '0028p langgan',
 '007',
 '007 dir',
 '008',
 '008 00',
 '008 008',
 '008 088',
 '008 dir',
 '008 ke2023',
 '0088',
 '0088 perdir',
 '0088 polisi',
 '0088z',
 '0088z baru',
 '008z',
 '008z bacabaca',
 '008z baru',
 '008z layan',
 '01',
 '0163',
 '0163 0088',
 '02',
 '02 ohm',
 '028',
 '028 028',
 '028 10',
 '028 2023',
 '028 app',
 '028 awalawal',
 '028 baca',
 '028 baru',
 '028 beda',
 '028 berita',
 '028 biaya',
 '028 bunyi',
 '028 cetak',
 '028 dasar',
 '028 detail',
 '028 erti',
 '028 evaluasi',
 '028 hitung',
 '028 ingat',
 '028 insya',
 '028 kategori',
 '028 kondisi',
 '028 laksana',
 '028 lambat',
 '028 langgan',
 '028 lengkap',
 '028 lihat',
 '028 maaf',
 '028 meja',
 '028 mencatumkan',
 '028 nama',
 '028 nomor',
 '028 oke',
 '028 organisasi',
 '028 p2',
 '028 padam',
 '028 panggil',
 '028 pasti',
 '028 perdir',
 '028 prosedur',
 '028 rusak',
 '028 sertifikat',
 '028 situ',
 '028 surat',
 '028 syarat',
 '028 tawar',
 '028 tetap',
 '028 tugas',
 '028p',
 '028p garing',
 '08',
 '08 08',
 '08 082023',
 '08 2016',
 '08 perdir',
 '082023',
 '082023 enggak',
 '088',
 '088 088',
 '088 2016',
 '088 ah',
 '088 ganti',
 '088 kait',
 '088 lain',
 '088 organisasi',
 '088 surat',
 '088 tahu',
 '088 tidak',
 '088 tugas',
 '088 update',
 '088 zp',
 '0880',
 '0880 p2880',
 '088j',
 '088z',
 '088z belum',
 '10',
 '10 10',
 '10 amper',
 '10 ampere',
 '10 diniang',
 '10 kategori',
 '10 kayak',
 '10 kerja',
 '10 kunci',
 '10 langgar',
 '10 lihat',
 '10 meter',
 '10 minus',
 '10 perdir',
 '10 senti',
 '10 tidak',
 '100',
 '100 1005',
 '100 200',
 '100 jam',
 '1005',
 '1005 2005',
 '1005 faktor',
 '1005 rubah',
 '105',
 '105 205',
 '105 rubah',
 '10a',
 '10a maksud',
 '12',
 '12 12',
 '12 24',
 '12 enggak',
 '12 kali',
 '12 maksimal',
 '12 orang',
 '12 surat',
 '12 tidak',
 '12 unit',
 '12 usernya',
 '13',
 '13 ayat',
 '1300',
 '14',
 '14 pasal',
 '1486',
 '15',
 '15 kerja',
 '15 persen',
 '163',
 '163 163',
 '163 2012',
 '163 bagus',
 '163 instalasi',
 '163 izin',
 '163 masuk',
 '163 nama',
 '163 oke',
 '163 panggil',
 '163 perdir',
 '163 periksa',
 '163 tumpang',
 '19',
 '19 ayat',
 '19 ayatc',
 '19 langgan',
 '19 levering',
 '19 pasal',
 '1x',
 '1x biaya',
 '1x daya',
 '1x rupiah',
 '20',
 '20 contoh',
 '20 faktor',
 '20 jam',
 '20 langgan',
 '20 pakketika',
 '20 pasca',
 '20 perdir',
 '20 putus',
 '20 tangguh',
 '200',
 '200 faktor',
 '200 tidak',
 '2000',
 '2000 kemarin',
 '2003',
 '2003 masuk',
 '2005',
 '2005 kasus',
 '2005 kau',
 '2005 lain',
 '2005 langgar',
 '2005 pengaruh',
 '2009',
 '2009 atur',
 '2009 perdir',
 '2009 rangka',
 '2009 tenaga',
 '2012',
 '2012 berita',
 '2013',
 '2013 baca',
 '2016',
 '2016 88z',
 '2016 enggak',
 '2016 kait',
 '2016 perdir',
 '2016 pln',
 '2016 salah',
 '2016an',
 '2016an seolaholah',
 '2019',
 '2019 lengkap',
 '2019 semenjak',
 '2020',
 '2020 angkat',
 '2020 kepala',
 '2020 tidak',
 '2021',
 '2021 2022',
 '2021 enggak',
 '2022',
 '2022 0088z',
 '2022 2021',
 '2022 2023',
 '2022 april',
 '2022 bulanbulan',
 '2022 gabung',
 '2022 juli',
 '2022 kali',
 '2022 mei',
 '2022 perdir',
 '2022 tengah',
 '2022 tidak',
 '2023',
 '2023 0028',
 '2023 0028p',
 '2023 028',
 '2023 2020',
 '2023 alat',
 '2023 baru',
 '2023 belum',
 '2023 bu',
 '2023 buka',
 '2023 bukabuka',
 '2023 dasar',
 '2023 dlpd',
 '2023 juli',
 '2023 juni',
 '2023 kemarin',
 '2023 kerja',
 '2023 ketentuanketentuan',
 '2023 kurang',
 '2023 laksana',
 '2023 langgan',
 '2023 lengkap',
 '2023 maksud',
 '2023 maret',
 '2023 minimal',
 '2023 mohon',
 '2023 nomor',
 '2023 oke',
 '2023 p1',
 '2023 p2tl',
 '2023 pakai',
 '2023 payung',
 '2023 pindah',
 '2023 segel',
 '2023 seharihari',
 '2023 selamat',
 '2023 situ',
 '2023 surat',
 '2023 syarat',
 '2023 tanggal',
 '2023 tidak',
 '2023 utama',
 '2023 vendor',
 '20232024',
 '20232024 mutasi',
 '2024',
 '2024 pindah',
 '2025',
 '2025 laksana',
 '205',
 '205 enggak',
 '205 jenis',
 '21',
 '21 ayat',
 '21 coba',
 '21 kaji',
 '21 pasal',
 '21 pasar',
 '21 putus',
 '23',
 '23 desember',
 '24',
 '24 24',
 '24 gm',
 '24 kali',
 '24 maksimal',
 '28',
 '28 15',
 '28 2023',
 '28 agakagak',
 '28 ayat',
 '28 case',
 '28 diri',
 '28 sertifikasi',
 '2x',
 '2x 720',
 '2x daya',
 '30',
 '30 2009',
 '30 2016',
 '30 2022',
 '30 anggap',
 '30 belum',
 '30 kali',
 '30 nyicil',
 '30 persen',
 '33',
 '33 minus',
 '33 persen',
 '35',
 '37',
 '3nya',
 '3nya habis',
 '3x',
 '40 40',
 '40 500',
 '40 502',
 '40 bayar',
 '40 normal',
 '40 nyala',
 '40 persen',
 '400',
 '400 jam',
 '45',
 '45 enggak',
 '500',
 '500 p1',
 '502',
 '502 atur',
 '539',
 '539 2023',
 '56',
 '56 menit',
 '66',
 '66 ukur',
 '6a',
 '6a 10a',
 '6x',
 '6x 2x',
 '720',
 '720 400',
 '720 jam',
 '720 kali',
 '73',
 '73 2020',
 '86',
 '86 ubah',
 '88',
 '88 2009',
 '88 bukti',
 '88 nomor',
 '88 perdir',
 '88 tidak',
 '888z',
 '888z belum',
 '88z',
 '88z 88z',
 '88z pembasaran',
 '9x',
 '9x 2x',
 '9x720',
 '9x720 jam',
 'a1',
 'a1 a1',
 'a1 informen',
 'a1 nyaksir',
 'abp',
 'absolut',
 'absolute',
 'acara',
 'acara alat',
 'acara aman',
 'acara ambil',
 'acara arus',
 'acara atur',
 'acara baca',
 'acara barang',
 'acara bawa',
 'acara bbnya',
 'acara belum',
 'acara berkas',
 'acara bongkar',
 'acara bu',
 'acara buka',
 'acara butuh',
 'acara coba',
 'acara ditandatangan',
 'acara dokumen',
 'acara dokumendokumen',
 'acara enggak',
 'acara evaluasi',
 'acara form',
 'acara halaman',
 'acara halo',
 'acara hasil',
 'acara identitas',
 'acara indikasiindikasi',
 'acara input',
 'acara inti',
 'acara isi',
 'acara kait',
 'acara kece',
 'acara kena',
 'acara kondisi',
 'acara laksana',
 'acara langgan',
 'acara langgar',
 'acara lapang',
 'acara lembar',
 'acara lengkap',
 'acara listlist',
 'acara log',
 'acara mohon',
 'acara nama',
 'acara oke',
 'acara p2tl',
 'acara panggil',
 'acara pas',
 'acara pasca',
 'acara pengaruh',
 'acara penting',
 'acara perdir',
 'acara perhati',
 'acara periksa',
 'acara pinjam',
 'acara polisi',
 'acara putih',
 'acara putus',
 'acara rangkap',
 'acara rubah',
 'acara salah',
 'acara serah',
 'acara sesuai',
 'acara sph',
 'acara sphnya',
 'acara surat',
 'acara suratsurat',
 'acara suruh',
 'acara tanda',
 'acara tanggal',
 'acara tangguh',
 'acara tawar',
 'acara temu',
 'acara tetap',
 'acara tidak',
 'acara tim',
 'acara tindak',
 'acara tuang',
 'acara tugas',
 'acara tulis',
 'acara ulp',
 'acara versiternya',
 'acara warna',
 'acaraberita',
 'acaraberita acara',
 'acmt',
 'acmt hasil',
 'acu',
 'acu dasar',
 'acu perdir',
 'ada',
 'adaada',
 'adaada bukti',
 'adakan',
 'adil',
 'adil kalah',
 'adm',
 'adm tetap',
 'admin',
 'admin langgan',
 'admin p2tl',
 'admin p2tlnya',
 'admin terima',
 'admin tetap',
 'administrasi',
 'administrasi administrasi',
 'administrasi adminnya',
 'administrasi alam',
 'administrasi ba',
 'administrasi banya',
 'administrasi berat',
 'administrasi berita',
 'administrasi berkas',
 'administrasi dasar',
 'administrasi dulunya',
 'administrasi hasil',
 'administrasi hitung',
 'administrasi ingat',
 'administrasi jabat',
 'administrasi kirakira',
 'administrasi koordinasi',
 'administrasi laksana',
 'administrasi langgan',
 'administrasi langsung',
 'administrasi lapang',
 'administrasi layan',
 'administrasi level',
 'administrasi levering',
 'administrasi mutasi',
 'administrasi nagih',
 'administrasi opsi',
 'administrasi p2tl',
 'administrasi perdir',
 'administrasi perdirnya',
 'administrasi posisi',
 'administrasi ren',
 'administrasi sambung',
 'administrasi seharihari',
 'administrasi selesai',
 'administrasi sisi',
 'administrasi surat',
 'administrasi terima',
 'administrasi tidak',
 'administrasi verifikasi',
 'adminnya',
 'adminnya evaluasi',
 'adminstrasi',
 'admnya',
 'aduh',
 'aduh nesan',
 'aerometer',
 'aerometer rct',
 'agakagak',
 'agakagak lupa',
 'ah',
 'ah 088',
 'ah enggak',
 'ah langgar',
 'ah manusia',
 'ah salah',
 'ah surat',
 'air',
 'ajar paham',
 'ajar perdir',
 'ajar temu',
 'aju',
 'aju aju',
 'aju berat',
 'aju lab',
 'aju lambat',
 'aju langgan',
 'aju level',
 'aju surat',
 'aju tim',
 'akhir',
 'akhir enggak',
 'akhir tidak',
 'akhirakhir',
 'akhirakhir administrasi',
 'akibat',
 'akibat nilai',
 'akibat potong',
 'akibat rusa',
 'akreditasi',
 'akreditasi biaya',
 'akreditasi menteri',
 'akreditasi pilih',
 'aktif',
 'aktif lihat',
 'aktif p2tl',
 'aktivitas',
 'aku',
 'aku kait',
 'akumulasi',
 'akumulasi eksporimpornya',
 'akurasi',
 'akurat',
 'ala',
 'alam',
 'alam 163',
 'alam alam',
 'alam contoh',
 'alam gantung',
 'alam k2',
 'alam kategori',
 'alam korosi',
 'alam lain',
 'alam langgan',
 'alam langsung',
 'alam manusia',
 'alam masuk',
 'alam orang',
 'alam perdir',
 'alam sisi',
 'alam tidak',
 'alam timbul',
 'alam ukur',
 'alam urgency',
 'alamat',
 'alamat ktp',
 'alamat langgan',
 'alamat sesuai',
 'alamat tugas',
 'alami',
 'alami pertamatama',
 'alami pisah',
 'alas',
 'alas anak',
 'alat',
 'alat apd',
 'alat apt',
 'alat bagi',
 'alat batas',
 'alat berita',
 'alat bongkarbongkar',
 'alat bukti',
 'alat checklist',
 'alat dukung',
 'alat empat',
 'alat indikasi',
 'alat k3',
 'alat kartu',
 'alat kategori',
 'alat kendali',
 'alat kerja',
 'alat laksana',
 'alat langgan',
 'alat lengkap',
 'alat lindung',
 'alat listrik',
 'alat p2tl',
 'alat pengukurpembatas',
 'alat siap',
 'alat tang',
 'alat tangga',
 'alat tiga',
 'alat tim',
 'alat tool',
 'alat tukur',
 'alat uji',
 'alatalat',
 'alatalat kerja',
 'alatalat luka',
 'alatalat manusia',
 'alatalat sesuai',
 'alatalat tulis',
 'alatalatnya',
 'alatalatnya calnet',
 'alhamdulillah',
 'alhamdulillah enggak',
 'alhamdulillah pokok',
 'alhamdulillah rutin',
 'alidaya',
 'alidaya pln',
 'alih teknik',
 'alir',
 'alir listrik',
 'allah kuat',
 'allah pindah',
 'allah rumah',
 'allah tugas',
 'allah up3',
 'alun',
 'alun tang',
 'alur',
 'aman',
 'aman aman',
 'aman barang',
 'aman damping',
 'aman dapat',
 'aman guna',
 'aman hasil',
 'aman ini',
 'aman jiwa',
 'aman lapang',
 'aman makan',
 'aman objek',
 'aman pakai',
 'aman polisi',
 'aman ppns',
 'aman putus',
 'aman syarat',
 'aman tidak',
 'aman tiga',
 'aman vital',
 'amanah',
 'amanah staf',
 'ambil',
 'ambil amikon',
 'ambil barang',
 'ambil bersamasama',
 'ambil data',
 'ambil desain',
 'ambil dlpd',
 'ambil duaduanya',
 'ambil eviden',
 'ambil isi',
 'ambil jam',
 'ambil langgan',
 'ambil lbkb',
 'ambil level',
 'ambil listrik',
 'ambil merah',
 'ambil p1',
 'ambil perdir',
 'ambil polisi',
 'ambil sadap',
 'ambil sir',
 'ambil sisi',
 'ambil sopan',
 'ambil tidak',
 'amikon',
 'amikon cari',
 'amikon harap',
 'amikon kelainankelainannya',
 'amikon lihat',
 'amikon pas',
 'amikon tegang',
 'amin',
 'amin sebudin',
 'amper',
 'amper alat',
 'amper amper',
 'amper banding',
 'amper cek',
 'amper curiga',
 'amper dicatok',
 'amper kabel',
 'amper kece',
 'amper lihat',
 'amper modu',
 'amper multimeter',
 'amper multiresor',
 'amper ngukur',
 'amper oke',
 'amper pakai',
 'amper pas',
 'amper selisih',
 'amper sisi',
 'amper situ',
 'amper tang',
 'amper tibatiba',
 'amper tool',
 'ampere',
 'ampere banding',
 'ampere kena',
 'ampere kontrak',
 'ampere langgan',
 'ampere langgar',
 'ampere pasang',
 'ampere tim',
 'ampere ukur',
 'ampermeter',
 'ampermeter ampermeter',
 'ampermeter dicatok',
 'ampermeter ukur',
 'ampernya',
 'amplop',
 'amplop barang',
 'ampung',
 'ampung bongkar',
 'amr',
 'amr instan',
 'amr jaga',
 'amr lbkb',
 'amr load',
 'amr pas',
 'amr perdir',
 'amr sudut',
 'anak',
 'anak bayi',
 'anak buah',
 'anak butuh',
 'anak rumah',
 'analisa',
 'analisa beli',
 'analisa data',
 'analisa dianalisa',
 'analisa evaluasi',
 'analisa hasil',
 'analisa lapor',
 'analisa tlte',
 'analisanya',
 'analisis',
 'analisis ba',
 'analog',
 'ancam',
 'ancam sehat',
 'anda',
 'anda berat',
 'anda meter',
 'anda temu',
 'andal',
 'andalas',
 'andalas 2022',
 'andalas lengkap',
 'anef',
 'aneh',
 'aneh langgan',
 'anepnya',
 'anev berita',
 'anev kantor',
 'anev tim',
 'anevnya',
 'anfnya',
 'anfnya layan',
 'anfnya masuk',
 'anggap',
 'anggap macet',
 'anggar',
 'anggar biaya',
 'anggar enggak',
 'anggar langgan',
 'anggota',
 'angin',
 'angka',
 'angkat',
 'angkat 73',
 'angkat app',
 'angkat s1',
 'angkut',
 'angsur',
 'angsur bu',
 'angsur cicil',
 'angsur izin',
 'angsur kali',
 'anomali anomali',
 'anomali informasi',
 'anomali kadangkadang',
 'anomali pakai',
 'anomali ukur',
 'anomali ungkos',
 'anomalianomali',
 'anomalianomali amikon',
 'anomalianomalinya',
 'anomalianomalinya oke',
 'antar',
 'anu isi',
 'anu salah',
 'anu undangundang',
 'ap2t',
 'ap2t 10',
 'ap2t ap2t',
 'ap2t dlpd',
 'ap2t langsung',
 'ap2t rumus',
 'ap2t sesuai',
 'ap2tnya',
 'apa',
 'apa apa',
 'apa cek',
 'apa jenis',
 'apa kwh',
 'apa tambah',
 'apa tidak',
 'apaapa',
 'apaapa atur',
 'apaapa bentar',
 'apaapa enggak',
 'apaapa p2tl',
 'apaapa pegang',
 'apaapa posisi',
 'apaapa tim',
 'aparat',
 'aparat aparat',
 'aparat besa',
 'aparat lingkung',
 'apb maaf',
 'apbku',
 'apbnya rusak',
 'apbnya tidak',
 'apcdtnya',
 'apcdtnya wp',
 'apd',
 'apd alat',
 'apd apd',
 'apd apdnya',
 'apd dasar',
 'apd dokumen',
 'apd helm',
 'apd hitung',
 'apd kawankawan',
 'apd kesiap',
 'apd lat',
 'apd lengkap',
 'apd safety',
 'apd sendiri',
 'apd siap',
 'apd sop',
 'apd toolkit',
 'apd tugas',
 'apdnya',
 'apdnya lengkap',
 'apj',
 'apj siap',
 'aplikasi',
 'aplikasi amikon',
 'aplikasi ap2t',
 'aplikasi aplikasi',
 'aplikasi dasardasarnya',
 'aplikasi enggak',
 'aplikasi epm',
 'aplikasi faktor',
 'aplikasi hitung',
 'aplikasi ipm',
 'aplikasi langgan',
 'aplikasi langsung',
 'aplikasi masuk',
 'aplikasi menginput',
 'aplikasi p2tl',
 'aplikasi pakai',
 'aplikasi situ',
 'aplok',
 'aplok tutup',
 'app',
 'app alat',
 'app aman',
 'app app',
 'app batas',
 'app bawa',
 'app bongkar',
 'app data',
 'app enggak',
 'app error',
 'app ganti',
 'app hasil',
 'app karat',
 'app langgan',
 'app lengkap',
 'app netral',
 'app padam',
 'app pas',
 'app periksa',
 'app pln',
 'app rusak',
 'app simpul',
 'app sr',
 'app srappnya',
 'app tanda',
 'app tetangga',
 'app tidak',
 'appnya',
 'appnya ambil',
 'appnya amper',
 'appnya angkut',
 'appnya belum',
 'appnya bongkar',
 'appnya bukti',
 'appnya data',
 'appnya netral',
 'appnya padam',
 'appnya serah',
 'april',
 'april enggak',
 ...]

In [88]:
# membuat vocabulary baru berdasarkan fitur yang terseleksi

new_selected_feature = {}

for (k,v) in vec_TF_IDF.vocabulary_.items():
    if k in selected_feature:
        new_selected_feature[k]=v

new_selected_feature

{'situ': 17656,
 'surat': 18168,
 'isi': 7235,
 'berita': 3294,
 'acara': 707,
 'belum': 3031,
 'ini': 7111,
 'meriksa': 12105,
 'dokumen': 5353,
 'dokumendokumen': 5383,
 'ba': 2305,
 'izin': 7327,
 'masuk': 11715,
 'lokasi': 11260,
 'temu': 18972,
 'hasil': 6544,
 'periksa': 14892,
 'langgan': 9860,
 'datang': 4802,
 'selesai': 17032,
 'serah': 17183,
 'administrasi': 905,
 'barang': 2643,
 'bukti': 3835,
 'lapang': 10465,
 'segel': 16874,
 'rusak': 16419,
 'posisi': 15519,
 'mcb': 11879,
 'b1': 2241,
 'level': 10933,
 'kali': 8011,
 'tidak': 19419,
 'hitung': 6687,
 'ketemu': 8818,
 'teman': 18877,
 'penting': 14717,
 'terima': 19215,
 'alam': 1114,
 'jenis': 7647,
 'situ surat': 17731,
 'surat tugas': 18214,
 'tugas isi': 20360,
 'isi berita': 7245,
 'berita acara': 3296,
 'acara belum': 724,
 'belum isi': 3057,
 'isi langsung': 7259,
 'langsung ini': 10369,
 'ini meriksa': 7118,
 'meriksa dokumen': 12106,
 'dokumen situ': 5376,
 'situ berita': 17670,
 'acara dokumendokumen': 739,
 'dokumendokumen ba': 5384,
 'ba surat': 2340,
 'surat izin': 18185,
 'masuk lokasi': 11771,
 'lokasi langgar': 11279,
 'langgar temu': 10306,
 'temu langgar': 19025,
 'langgar hasil': 10228,
 'hasil temu': 6604,
 'hasil periksa': 6594,
 'periksa langgan': 14976,
 'langgan datang': 9940,
 'datang langgan': 4806,
 'selesai langgan': 17052,
 'kantor selesai': 8169,
 'selesai bawa': 17034,
 'bawa berita': 2765,
 'acara serah': 819,
 'serah administrasi': 17184,
 'administrasi banya': 915,
 'banya barang': 2611,
 'barang bukti': 2646,
 'bukti temu': 3924,
 'temu temu': 19071,
 'temu lapang': 19027,
 'lapang segel': 10566,
 'segel rusak': 16910,
 'rusak gantung': 16426,
 'gantung posisi': 6272,
 'posisi periksa': 15535,
 'periksa segel': 15024,
 'rusak mcb': 16432,
 'mcb b1': 11884,
 'b1 level': 2250,
 'laksana lapang': 9709,
 'lapang cari': 10492,
 'cari kali': 4073,
 'tidak hitung': 19523,
 'hitung kali': 6703,
 'kali surat': 8059,
 'lokasi nama': 11285,
 'nama hasil': 12565,
 'hasil ketemu': 6578,
 'ketemu temu': 8835,
 'lapang bagi': 10484,
 'bagi periksa': 2458,
 'periksa teman': 15045,
 'teman khusus': 18883,
 'khusus isi': 8872,
 'acara penting': 799,
 'penting hasil': 14719,
 'temu sma': 19066,
 'sma terima': 17813,
 'terima sma': 19237,
 'sma baru': 17800,
 'baru belum': 2674,
 'belum belum': 3042,
 'belum alam': 3034,
 'alam gantung': 1120,
 'posisi belum': 15522,
 'belum temu': 3121,
 'tidak jenis': 19549,
 'kancing': 8106,
 '028': 90,
 '2023': 425,
 'juni': 7735,
 'data': 4699,
 'huni': 6809,
 'tarif': 18679,
 'daya': 4812,
 'alamat': 1148,
 'tanda': 18497,
 'tangan': 18521,
 'contoh': 4312,
 'kategori': 8294,
 'maaf': 11398,
 'lupa': 11347,
 'p1': 13305,
 'baca': 2353,
 'p2': 13390,
 'admin': 894,
 'simpan': 17504,
 'tetap': 19321,
 'ap2t': 1748,
 'sesuai': 17307,
 'jurnis': 7743,
 'panggil': 14081,
 'jarak': 7556,
 'dasar': 4621,
 'piak': 15205,
 'lengkap foto': 10835,
 'foto belum': 6149,
 'belum kancing': 3062,
 'kancing 028': 8107,
 '028 028': 91,
 '028 2023': 95,
 '2023 juni': 449,
 'juni juni': 7737,
 'juni 2023': 7736,
 '2023 situ': 486,
 'situ isi': 17687,
 'isi data': 7249,
 'data langgan': 4738,
 'langgan data': 9938,
 'langgan huni': 9970,
 'huni tarif': 6812,
 'daya alamat': 4819,
 'alamat tugas': 1158,
 'periksa jenis': 14956,
 'jenis temu': 7663,
 'temu tanda': 19067,
 'tanda tangan': 18500,
 'saksi tugas': 16575,
 'tugas contoh': 20333,
 'contoh besar': 4318,
 'besar batas': 3376,
 'batas masuk': 2732,
 'masuk langgar': 11764,
 'langgar kategori': 10241,
 'kategori langgar': 8308,
 'langgar besar': 10216,
 'daya maaf': 4862,
 'maaf lupa': 11413,
 'lupa p1': 11375,
 'p1 baca': 13309,
 'baca 028': 2355,
 '028 p2': 154,
 'p2 maaf': 13421,
 'lupa admin': 11349,
 'admin terima': 902,
 'terima berita': 19219,
 'acara hasil': 748,
 'temanteman lapang': 18914,
 'lapang simpan': 10572,
 'simpan dokumen': 17505,
 'dokumen hasil': 5362,
 'bukti bawa': 3849,
 'bawa temanteman': 2798,
 'temanteman nama': 18918,
 'nama dokumen': 12556,
 'dokumen tetap': 5381,
 'tetap ap2t': 19324,
 'ap2t sesuai': 1761,
 'sesuai jurnis': 17349,
 'jurnis langgar': 7744,
 'langgar maksud': 10265,
 'maksud surat': 11589,
 'panggil berita': 14096,
 'acara langgan': 766,
 'langgan tidak': 10173,
 'tidak langgan': 19584,
 'langgan panggil': 10076,
 'panggil panggil': 14150,
 'acara tugas': 846,
 'tugas lapang': 20383,
 'lapang temanteman': 10585,
 'lapang panggil': 10551,
 'panggil tidak': 14176,
 'tidak buat': 19470,
 'buat panggil': 3781,
 'panggil jarak': 14121,
 'tidak panggil': 19650,
 'panggil tiga': 14177,
 'tiga panggil': 19812,
 'tiga tidak': 19824,
 'tidak belum': 19456,
 'belum baca': 3037,
 'baca tidak': 2435,
 'tidak paham': 19648,
 'paham tetap': 13912,
 'tetap dasar': 19331,
 'dasar berita': 4630,
 'tidak tidak': 19746,
 'buat tetap': 3788,
 'tetap piak': 19363,
 'piak panggil': 15206,
 'layan': 10661,
 'transaksi': 20211,
 'energi': 5611,
 'p2tl': 13486,
 'kemarin': 8518,
 'enggak': 5665,
 'murni': 12487,
 'melobby': 12014,
 'komplain': 9032,
 'bantu': 2593,
 'media': 11986,
 'halo': 6490,
 'kirim': 8932,
 'terus': 19283,
 'minggu': 12300,
 'ikut': 6877,
 'perdir': 14781,
 '88': 664,
 'jadwal': 7447,
 'lihat': 11073,
 'nomor': 12810,
 'tanggal': 18572,
 'serta': 17239,
 'jabat': 7390,
 'sambung': 16690,
 'ambil': 1355,
 'meter': 12127,
 'kwh': 9422,
 'tim': 19832,
 'ketua': 8850,
 'app': 1900,
 'merek': 12101,
 'pasang': 14347,
 'kotak': 9282,
 'simpul': 17517,
 'sengaja': 17136,
 'tau': 18701,
 'izin layan': 7358,
 'layan langgan': 10669,
 'langgan surat': 10150,
 'surat tidak': 18211,
 'tidak tetap': 19745,
 'tetap transaksi': 19383,
 'transaksi energi': 20214,
 'p2tl maret': 13622,
 'maret kemarin': 11691,
 'tugas enggak': 20344,
 'enggak surat': 5800,
 'tugas foto': 20346,
 'foto tetap': 6160,
 'tetap murni': 19354,
 'murni transaksi': 12488,
 'energi layan': 5634,
 'langgan melobby': 10042,
 'melobby langgan': 12015,
 'langgan komplain': 10007,
 'komplain bantu': 9033,
 'bantu media': 2600,
 'media tetap': 11989,
 'tetap halo': 19335,
 'halo halo': 6491,
 'halo tidak': 6497,
 'tidak hadir': 19517,
 'hadir kali': 6453,
 'panggil kirim': 14133,
 'panggil enggak': 14110,
 'enggak terus': 5811,
 'terus surat': 19286,
 'jarak jarak': 7559,
 'jarak minggu': 7561,
 'minggu ikut': 12306,
 'ikut perdir': 6889,
 'perdir 88': 14797,
 '88 perdir': 668,
 'perdir belum': 14807,
 'belum panggil': 3092,
 'enggak masuk': 5751,
 'masuk panggil': 11783,
 'tiga jadwal': 19793,
 'jadwal minggu': 7453,
 'minggu perdir': 12311,
 'surat ba': 18171,
 'ba lihat': 2331,
 'lihat nomor': 11113,
 'nomor surat': 12843,
 'surat tanggal': 18206,
 'tanggal nama': 18578,
 'langgan nama': 10051,
 'tugas serta': 20431,
 'serta jabat': 17247,
 'jabat nama': 7402,
 'alamat langgan': 1153,
 'sambung untuk': 16721,
 'untuk data': 20982,
 'data barang': 4709,
 'bukti ambil': 3841,
 'ambil isi': 1373,
 'isi meter': 7265,
 'meter kwh': 12178,
 'kwh tim': 9472,
 'p2tl ketua': 13599,
 'ketua tugas': 8856,
 'tugas sidik': 20436,
 'sidik saksi': 17476,
 'saksi periksa': 16567,
 'periksa app': 14905,
 'app periksa': 1929,
 'app data': 1910,
 'kwh merek': 9449,
 'merek putar': 12103,
 'putar segel': 15807,
 'segel pasang': 16905,
 'pasang batas': 14350,
 'batas kotak': 2726,
 'kotak app': 9283,
 'app simpul': 1933,
 'periksa tindak': 15055,
 'tindak segel': 19934,
 'rusak masuk': 16431,
 'p2 rusak': 13440,
 'rusak rusak': 16436,
 'rusak sengaja': 16438,
 'sengaja belum': 17137,
 'belum p2': 3088,
 'p2 tau': 13447,
 'tau p2tl': 18710,
 'p2tl p2tl': 13636,
 'p2tl ikut': 13574,
 'ikut 2023': 6879,
 '2023 belum': 436,
 'belum tau': 3119,
 'join': 7684,
 'balancenya': 2511,
 'dinamis': 5149,
 'mutasi': 12491,
 'upload': 21042,
 'pindah': 15230,
 'sales': 16671,
 'retail': 16195,
 'coba': 4281,
 'caricari': 4087,
 'panjang': 14188,
 'bidang': 3449,
 'pakai': 13914,
 'salah': 16582,
 'perdirnya': 14842,
 'ingat': 7040,
 'jangka': 7532,
 'bongkar': 3603,
 'habis': 6413,
 'administrasi posisi': 960,
 'posisi tidak': 15540,
 'tidak tangan': 19732,
 'tangan p2tl': 18540,
 'p2tl join': 13584,
 'join tau': 7685,
 'tau balancenya': 18702,
 'balancenya dinamis': 2512,
 'dinamis tidak': 5150,
 'tidak tau': 19736,
 'tau tibatiba': 18711,
 'tibatiba mutasi': 19414,
 'mutasi upload': 12506,
 'upload 2023': 21043,
 '2023 pindah': 479,
 'pindah sales': 15246,
 'sales retail': 16673,
 'retail coba': 16196,
 'coba izin': 4294,
 'izin caricari': 7340,
 'caricari panjang': 4088,
 'panjang administrasi': 14189,
 'administrasi perdir': 958,
 'perdir 028': 14786,
 '028 perdir': 158,
 '028 insya': 128,
 'allah pindah': 1294,
 'pindah pindah': 15243,
 'pindah bidang': 15231,
 'bidang baca': 3450,
 'baca pakai': 2414,
 'pakai 2023': 13919,
 '2023 tidak': 495,
 'tidak salah': 19697,
 'salah perdirnya': 16651,
 'perdirnya surat': 14861,
 'panggil ingat': 14117,
 'ingat terbit': 7101,
 'terbit jangka': 19195,
 'jangka ingat': 7535,
 'terbit tidak': 19203,
 'langgan terbit': 10165,
 'terbit ingat': 19194,
 'ingat ingat': 7062,
 'ingat tidak': 7105,
 'tidak bongkar': 19467,
 'bongkar tidak': 3652,
 'tidak ingat': 19532,
 'ingat bongkar': 7050,
 'bongkar ingat': 3617,
 'ingat habis': 7060,
 'habis jangka': 6427,
 'jangka langsung': 7539,
 'langsung tugas': 10439,
 'tugas bongkar': 20329,
 'ingat 028': 7041,
 '028 nama': 148,
 'nama barang': 12544,
 'bukti tau': 3922,
 'tau dokumen': 18704,
 'barang hasil': 2648,
 'periksa nama': 14995,
 'wpjsa': 21325,
 'kerja': 8677,
 'ranah': 15973,
 'hukum': 6766,
 'sertifikasi': 17256,
 'mesti': 12117,
 'pulang': 15750,
 'jsa': 7696,
 'formulir': 6144,
 'ktp': 9325,
 'menandatangani': 12027,
 'spesifikasi': 17927,
 'berkas': 3311,
 'manusia': 11667,
 'lain': 9579,
 'banget': 2581,
 'lampu': 9847,
 'aman': 1310,
 'alat': 1169,
 'lampung': 9852,
 'lanjut': 10447,
 'tagih': 18383,
 'bayar': 2814,
 'susul': 18249,
 'level tidak': 10999,
 'wajib wajib': 21244,
 'izin kerja': 7351,
 'kerja masuk': 8726,
 'masuk ranah': 11795,
 'ranah hukum': 15974,
 'dokumen p2tl': 5373,
 'p2tl surat': 13685,
 'tugas jsa': 20363,
 'kerja berita': 8691,
 'acara tidak': 841,
 'tidak berita': 19461,
 'p2tl tidak': 13701,
 'tidak surat': 19724,
 'formulir berita': 6145,
 'acara isi': 755,
 'isi lengkap': 7262,
 'lengkap isi': 10841,
 'langgan ktp': 10013,
 'temu tulis': 19078,
 'tulis sesuai': 20545,
 'sesuai temu': 17387,
 'temu data': 18993,
 'meter data': 12153,
 'berkas barang': 3316,
 'periksa perdir': 15011,
 'perdir nomor': 14818,
 'nomor 028': 12813,
 '028 app': 99,
 'app rusak': 1932,
 'rusak alam': 16420,
 'alam manusia': 1132,
 'kategori alam': 8295,
 'alam kategori': 1124,
 'kategori p1': 8313,
 'lain lain': 9610,
 'bongkar lampu': 3627,
 'langgan bongkar': 9922,
 'app aman': 1902,
 'lokasi kecuali': 11275,
 'bongkar lampung': 3628,
 'administrasi surat': 969,
 'surat tagih': 18205,
 'langgan layan': 10026,
 'pasang pasang': 14374,
 'bayar tagih': 2863,
 'tagih susul': 18407,
 'susul tetap': 18292,
 'tetap oke': 19357,
 'mbak': 11863,
 'seharihari': 16937,
 'mana': 11613,
 'koordinator': 9216,
 'skd': 17773,
 'bongkarampung': 3653,
 'tempat': 18945,
 'k1': 7755,
 'bbnya': 2889,
 'potong': 15563,
 'komplit': 9034,
 'coret': 4362,
 'uang': 20631,
 'akibat': 1063,
 'id': 6830,
 'rumah': 16321,
 'sekiansekian': 16989,
 'pengkarampung': 14708,
 'listrik': 11163,
 'laksana utama': 9764,
 'seharihari laksana': 16947,
 'p2tl lapang': 13611,
 'lapang kantor': 10517,
 '028 panggil': 156,
 'acara surat': 829,
 'ingat bongkarampung': 7051,
 'kabel tiang': 7832,
 'tugas tidak': 20453,
 'mbak surat': 11873,
 'laksana laksana': 9704,
 'briefing briefing': 3679,
 'briefing tim': 3688,
 'tim surat': 19888,
 'lain segel': 9627,
 'segel p2': 16904,
 'tim laksana': 19862,
 'data lengkap': 4743,
 'lengkap langgan': 10854,
 'p2tl lain': 13604,
 'lain langgar': 9613,
 'administrasi langsung': 937,
 'admin langgan': 897,
 'kantor tagih': 8177,
 'selesai tagih': 17072,
 'susul tagih': 18289,
 'susul serta': 18285,
 'serta surat': 17255,
 'ingat isi': 7063,
 'laksana surat': 9752,
 'panggil mohon': 14143,
 'kasih tau': 8268,
 'ingat selesai': 7093,
 'kantor tidak': 8181,
 'tidak kantor': 19553,
 'susul langsung': 18271,
 'langsung pasang': 10404,
 'atur': 2136,
 'direksi': 5177,
 '28': 545,
 'september': 17174,
 '30': 569,
 'hafal': 6460,
 'takut': 18465,
 'putus': 15821,
 'rampung': 15911,
 'diri': 5190,
 'abp': 692,
 'pelihara': 14601,
 'sebab': 16831,
 'p2l': 13467,
 'damping': 4553,
 'wenang': 21266,
 'saksisaksi': 16578,
 'mohon izin': 12408,
 'atur direksi': 2145,
 'direksi nomor': 5184,
 'nomor 28': 12817,
 '28 2023': 548,
 'mohon maaf': 12410,
 '2023 tanggal': 491,
 '30 belum': 574,
 'izin mohon': 7365,
 'maaf belum': 11404,
 'giat p2tl': 6322,
 'nama atur': 12540,
 'lupa bongkar': 11358,
 'bongkar langsung': 3630,
 'langsung panggil': 10401,
 'langsung putus': 10412,
 'putus putus': 15860,
 'putus panggil': 15855,
 'panggil putus': 14158,
 'bongkar rampung': 3639,
 'rampung langgan': 15943,
 'tidak bayar': 19454,
 'surat surat': 18204,
 'langsung bongkar': 10345,
 'rampung mohon': 15950,
 'segel segel': 16912,
 'segel mcb': 16899,
 'mcb mcb': 11910,
 'mcb contoh': 11891,
 'langgar korosi': 10249,
 'korosi segel': 9247,
 'segel korosi': 16894,
 'langgar tidak': 10311,
 'sebab langgan': 16835,
 'tugas surat': 20442,
 'nomor berita': 12823,
 'acara tanggal': 834,
 'tanggal periksa': 18580,
 'periksa data': 14931,
 'laksana p2tl': 9724,
 'p2tl data': 13546,
 'data damping': 4712,
 'wenang damping': 21267,
 'periksa tanda': 15041,
 'tangan tim': 18554,
 'berapa': 3201,
 'konsumen': 9113,
 'sepia': 17171,
 'bikin': 3482,
 'proses': 15690,
 'aparat': 1796,
 'rtb': 16274,
 'dianalisa': 5028,
 'pungkar': 15782,
 'rambut': 15908,
 'beda': 2938,
 '163': 307,
 'baru 028': 2668,
 'oke panggil': 13116,
 'panggil berapa': 14095,
 'berapa panggil': 3205,
 'panggil tagih': 14168,
 'ts ts': 20251,
 'bikin surat': 3486,
 'surat enggak': 18182,
 'enggak buat': 5691,
 'buat surat': 3786,
 'enggak belum': 5682,
 'belum situ': 3111,
 'situ proses': 17719,
 'proses panggil': 15707,
 'data periksa': 4760,
 'temanteman tugas': 18937,
 'tugas tugas': 20459,
 'tugas damping': 20336,
 'damping aparat': 4557,
 'kau meter': 8328,
 'periksa temu': 15047,
 'temu periksa': 19050,
 'tulis simpul': 20546,
 'simpul periksa': 17534,
 'periksa damping': 14928,
 'langsung pungkar': 10411,
 'proses selesai': 15710,
 'tugas kantor': 20366,
 'langgar batas': 10210,
 'batas p1': 2739,
 'alam tidak': 1143,
 'kategori kategori': 8305,
 'sengaja langgar': 17141,
 'langgar lain': 10250,
 '163 oke': 319,
 'identitas': 6840,
 'bapp': 2635,
 'bappnya': 2638,
 'dokumendokumennya': 5389,
 'terang': 19161,
 'appnya': 1945,
 'tipe': 19968,
 'mcbnya': 11938,
 'teknis': 18837,
 'ctptnya': 4416,
 'kece': 8415,
 'kondisi': 9050,
 'indikasi': 6943,
 'golong': 6345,
 'kepdir': 8661,
 'indah': 6924,
 'tagian': 18377,
 'sebentar': 16845,
 'jarang': 7568,
 'kait': 7899,
 'istilah': 7291,
 'acara periksa': 802,
 'identitas langgan': 6844,
 'kwh meter': 9450,
 'alat batas': 1181,
 'batas mcbnya': 2734,
 'ktp nomor': 9328,
 'periksa nomor': 14996,
 'data teknis': 4773,
 'app batas': 1906,
 'ganti app': 6229,
 'tidak batas': 19452,
 'kondisi segel': 9082,
 'aman tidak': 1344,
 'tidak simpul': 19713,
 'simpul temu': 17540,
 'temu indikasi': 19002,
 'indikasi langgar': 6954,
 'tidak hasil': 19520,
 'periksa masuk': 14991,
 'golong langgar': 6352,
 'enggak laksana': 5737,
 'tiga tetap': 19823,
 'tetap tagian': 19372,
 'tagian susul': 18380,
 'tindak putus': 19933,
 'tiga bongkar': 19783,
 'terima dokumen': 19221,
 'lapang terima': 10588,
 'terima barang': 19218,
 'lapang temu': 10586,
 'temu barang': 18982,
 'fisik fisik': 6094,
 'muncul': 12468,
 'idpel': 6855,
 'milik': 12280,
 'urus': 21057,
 'nasional': 12636,
 'sop': 17859,
 'k3nya': 7791,
 'aplikasi': 1861,
 'epm': 5835,
 'kayak': 8369,
 'simpel': 17514,
 'order': 13260,
 'tetangga': 19296,
 'perangkat': 14767,
 'desa': 4975,
 'rw': 16452,
 'kepala': 8657,
 'maju': 11485,
 'tidak muncul': 19615,
 'periksa p2l': 15002,
 'kait temu': 7985,
 'temu utama': 19085,
 'lengkap data': 10832,
 'periksa laksana': 14974,
 'laksana langgan': 9706,
 'langgan wakil': 10192,
 'wakil langgan': 21246,
 'langgan kait': 9992,
 'laksana hasil': 9692,
 'ukur lengkap': 20778,
 'lengkap berita': 10826,
 'tugas sop': 20438,
 'sop sop': 17883,
 'jarak surat': 7566,
 'rampung bongkar': 15921,
 'rampung pakai': 15955,
 'aplikasi epm': 1874,
 'order laksana': 13261,
 'laksana tugas': 9762,
 'p2tl wakil': 13718,
 'wakil tetangga': 21248,
 'perangkat desa': 14768,
 'masuk persil': 11790,
 'persil langgan': 15153,
 'langgan polisi': 10101,
 'polisi awas': 15453,
 'awas kerja': 2198,
 'tidak maksud': 19603,
 'ppns ppns': 15578,
 'fasa': 6041,
 'tr': 20202,
 'rubah': 16286,
 'rasio': 16020,
 'ct': 4384,
 'pengaruh': 14682,
 'mccbnya': 11966,
 'dokumentasi': 5393,
 'awal': 2183,
 'k2': 7758,
 'k3': 7770,
 'p4': 13797,
 'sah': 16515,
 'bahasa': 2481,
 'cek': 4123,
 'lapor': 10605,
 'tanggung': 18629,
 'institusi': 7181,
 'polres': 15504,
 'tni': 20034,
 'nunjukin': 12905,
 'laksana media': 9717,
 'p2tl laksana': 13605,
 'periksa fasa': 14942,
 'tidak langsung': 19586,
 'langsung ukur': 10441,
 'oke ukur': 13146,
 'langsung langgan': 10385,
 'langgan rubah': 10121,
 'rubah besar': 16292,
 'besar rasio': 3384,
 'rasio ct': 16022,
 'ct langgar': 4395,
 'tidak langgar': 19585,
 'langgar rubah': 10289,
 'rubah rasio': 16300,
 'p2 p2': 13430,
 'p2 ukur': 13452,
 'energi pengaruh': 5649,
 'energi p2': 5642,
 'periksa dokumentasi': 14936,
 'dokumentasi dokumentasi': 5398,
 'data app': 4706,
 'data hasil': 4720,
 'tangan tugas': 18555,
 'tugas langgan': 20380,
 'alam k2': 1122,
 'k2 k3': 7763,
 'perdirnya nomor': 14855,
 'nomor 163': 12815,
 'rampung temu': 15969,
 'temu p4': 19044,
 'p4 langgan': 13809,
 'langgan alat': 9875,
 'pakai berita': 13939,
 'acara bongkar': 727,
 'putus bahasa': 15828,
 'lapang bawa': 10486,
 'periksa kece': 14964,
 'cek hasil': 4154,
 'tanggung p2tl': 18641,
 'damping institusi': 4565,
 'langgan cek': 9929,
 'izin langgan': 7357,
 'langgan kece': 9998,
 'buat berita': 3772,
 'acara temu': 838,
 'tidak temu': 19739,
 'temu langgan': 19024,
 'dulunya': 5485,
 'supervisor': 18153,
 '088': 193,
 'pasar': 14386,
 'apaapa': 1783,
 'pertamatama': 15186,
 'alami': 1159,
 'baikbaik': 2505,
 'tahu': 18423,
 'izin administrasi': 7331,
 'administrasi dulunya': 923,
 'dulunya supervisor': 5487,
 'supervisor tidak': 18163,
 'salah 088': 16585,
 '088 088': 194,
 '088 lain': 202,
 'lain k3': 9605,
 'k3 tidak': 7788,
 'salah perdir': 16650,
 'perdir lain': 14814,
 '163 163': 308,
 '163 izin': 316,
 'izin belum': 7335,
 'belum izin': 3058,
 'maaf pindah': 11418,
 'pindah p3': 15240,
 'p3 pasar': 13786,
 'pasar tidak': 14398,
 'tidak apaapa': 19440,
 'apaapa pegang': 1792,
 'pegang izin': 14524,
 'izin pertamatama': 7373,
 'pertamatama langgan': 15189,
 'langgan temu': 10162,
 'temu alami': 18976,
 'alami pertamatama': 1162,
 'pertamatama izin': 15188,
 'izin dokumen': 7341,
 'dokumen temanteman': 5379,
 'lapang sesuai': 10570,
 'lapang hasil': 10508,
 'terima bukti': 19220,
 'bukti izin': 3878,
 'izin baikbaik': 7333,
 'baikbaik langgan': 2506,
 'periksa tahu': 15040,
 'tahu izin': 18431,
 'izin maaf': 7361,
 'maaf salah': 11422,
 'cerita': 4218,
 'ub3c': 20644,
 'pm': 15409,
 'orang': 13230,
 'mau': 11853,
 'ngerti': 12714,
 'sinomenya': 17561,
 'barubaru': 2697,
 'judul': 7720,
 'pirau': 15272,
 'orangorang': 13257,
 'ke1': 8385,
 'sadap': 16483,
 'maksimal': 11511,
 '502': 635,
 'jom': 7692,
 'biasa': 3411,
 'pas': 14247,
 'benerbener': 3150,
 'mnya': 12376,
 'buletan': 3956,
 'grondingnya': 6369,
 '02': 87,
 'ohm': 13043,
 'posisi laksana': 15530,
 'laksana panjang': 9727,
 'laksana kemarin': 9697,
 'kemarin cerita': 8530,
 'cerita ub3c': 4227,
 'ub3c periksa': 20645,
 'periksa pm': 15016,
 'pm orang': 15411,
 'orang orang': 13245,
 'orang mau': 13243,
 'mau panjang': 11854,
 'panjang panjang': 14215,
 'panjang diri': 14197,
 'diri baru': 5194,

In [89]:
len(new_selected_feature)

10000

In [90]:
# simpan vectorizer
pickle.dump(new_selected_feature,open("new_selected_feature_tf-idf_asesmen.pkl","wb"))

In [91]:
# menampilkan fitur-fitur yang sudah diseleksi

data_selected_feature = pd.DataFrame(x_kbest_features, columns=selected_feature)
data_selected_feature

,00,00 008,0023,0023 0163,0023 perdir,0028,0028 0028,0028 2023,0028 app,0028 baca,...,yuk,yuk istilah,yuk langgan,yuk tetangga,yuk tidak,zaman,zaman tl,zoom,zp,zp dir
0,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
291,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
292,0.0,0.0,0.0,0.0,0.0,0.047636,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
293,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
294,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
295,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## MODELLING

In [92]:
selected_x = x_kbest_features
selected_x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(296, 10000))

In [93]:
# import library
import random
from sklearn.model_selection import train_test_split

# import algoritma XGBoost
from xgboost import XGBClassifier

In [95]:
x = selected_x
y = data.label

x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

In [96]:
x

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(296, 10000))

In [97]:
y

0      0
1      0
2      0
3      1
4      1
      ..
291    1
292    1
293    1
294    1
295    1
Name: label, Length: 296, dtype: int64

In [98]:
# menampilkan jumlah data training dan data testing
print('Banyaknya X_train : ', len(x_train))
print('Banyaknya X_test : ', len(x_test))
print('Banyaknya Y_train : ', len(y_train))
print('Banyaknya Y_test : ', len(y_test))

Banyaknya X_train :  236
Banyaknya X_test :  60
Banyaknya Y_train :  236
Banyaknya Y_test :  60

In [99]:
# Proses training menggunakan XGBoost
text_algorithm = XGBClassifier(use_label_encoder=False, eval_metric='mlogloss')

In [100]:
model = text_algorithm.fit(x_train, y_train)

c:\Users\pjbac\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:199: UserWarning: [09:00:39] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)

## EVALUASI MODEL

In [101]:
# input library yang dibutuhkan untuk proses testing
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

predicted = model.predict(x_test)

CM = confusion_matrix(y_test, predicted)

print(classification_report(y_test, predicted))
print(confusion_matrix(y_test, predicted))

              precision    recall  f1-score   support

           0       1.00      0.82      0.90        11
           1       0.96      1.00      0.98        49

    accuracy                           0.97        60
   macro avg       0.98      0.91      0.94        60
weighted avg       0.97      0.97      0.97        60

[[ 9  2]
 [ 0 49]]

In [102]:
# menyimpan model
pickle.dump(model,open("model_asesmen.sav", "wb"))

In [103]:
import pandas as pd
import numpy as np
import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_selection import SelectKBest, chi2
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, confusion_matrix
from xgboost import XGBClassifier

# === Data Preparation ===
x = data['clean_teks']
y = data['label']

# === Pipeline: TF-IDF + Chi2 Feature Selection + XGBoost ===
pipeline = Pipeline([
    ('tfidf', TfidfVectorizer(ngram_range=(1,2))), # feature extraction
    ('select', SelectKBest(chi2, k=10000)),   # feature selection
    ('clf', XGBClassifier(use_label_encoder=False, eval_metric='mlogloss'))
])

# Split data
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=0)

# Train pipeline
pipeline.fit(x_train, y_train)

# Evaluate
y_pred = pipeline.predict(x_test)
print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

# Save pipeline
with open("pipeline_asesmen.pkl", "wb") as f:
    pickle.dump(pipeline, f)

              precision    recall  f1-score   support

           0       0.91      0.91      0.91        11
           1       0.98      0.98      0.98        49

    accuracy                           0.97        60
   macro avg       0.94      0.94      0.94        60
weighted avg       0.97      0.97      0.97        60

[[10  1]
 [ 1 48]]

c:\Users\pjbac\AppData\Local\Programs\Python\Python313\Lib\site-packages\xgboost\training.py:199: UserWarning: [09:00:45] WARNING: C:\actions-runner\_work\xgboost\xgboost\src\learner.cc:790:
Parameters: { "use_label_encoder" } are not used.

  bst.update(dtrain, iteration=i, fobj=obj)